<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ashley Dickson">
<meta name="dcterms.date" content="2026-07-21">

<title>Inequalities in Access to Neonatal Critical Care: Phase 1 Findings – NCC Inequalities Analysis</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-6b423f165eeea3787de40cb4f8e821c3.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">NCC Inequalities Analysis</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Overview</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./modelling_results.html" aria-current="page"> 
<span class="menu-text">Phase 1: Findings</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./technical_appendix.html"> 
<span class="menu-text">Phase 1: Technical Appendix</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#executive-summary" id="toc-executive-summary" class="nav-link active" data-scroll-target="#executive-summary"><span class="header-section-number">1</span> Executive Summary</a>
  <ul class="collapse">
  <li><a href="#key-messages" id="toc-key-messages" class="nav-link" data-scroll-target="#key-messages"><span class="header-section-number">1.1</span> Key Messages</a></li>
  </ul></li>
  <li><a href="#methods-in-brief" id="toc-methods-in-brief" class="nav-link" data-scroll-target="#methods-in-brief"><span class="header-section-number">2</span> Methods, in brief</a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results"><span class="header-section-number">3</span> Results</a>
  <ul class="collapse">
  <li><a href="#clinical-factors" id="toc-clinical-factors" class="nav-link" data-scroll-target="#clinical-factors"><span class="header-section-number">3.1</span> Clinical Factors</a></li>
  <li><a href="#ethnicity" id="toc-ethnicity" class="nav-link" data-scroll-target="#ethnicity"><span class="header-section-number">3.2</span> Ethnicity</a></li>
  <li><a href="#deprivation" id="toc-deprivation" class="nav-link" data-scroll-target="#deprivation"><span class="header-section-number">3.3</span> Deprivation</a></li>
  <li><a href="#hospital-variation" id="toc-hospital-variation" class="nav-link" data-scroll-target="#hospital-variation"><span class="header-section-number">3.4</span> Hospital Variation</a></li>
  <li><a href="#length-of-stay-and-mortality" id="toc-length-of-stay-and-mortality" class="nav-link" data-scroll-target="#length-of-stay-and-mortality"><span class="header-section-number">3.5</span> Length of Stay and Mortality</a></li>
  </ul></li>
  <li><a href="#recommendations" id="toc-recommendations" class="nav-link" data-scroll-target="#recommendations"><span class="header-section-number">4</span> Recommendations</a></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations"><span class="header-section-number">5</span> Limitations</a></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Inequalities in Access to Neonatal Critical Care: Phase 1 Findings</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Ashley Dickson </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 21, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>What changed in this revision (June–July 2026)
</div>
</div>
<div class="callout-body-container callout-body">
<p>This draft responds to feedback from Anna Everton and Katharine Robbins. Key changes:</p>
<ul>
<li><strong>[K3]</strong> Clarified that the cohort is babies <em>born</em> in 2023/24, not continuing-stay.</li>
<li><strong>[K5a]</strong> Rewrote variable selection around causal role (confounder / exposure / mediator), with a full candidate-variable table and the case against a data-driven (stepwise/LASSO) search for a causal access question.</li>
<li><strong>[A1]</strong> Rewrote the Chinese-group key message in plain language.</li>
<li><strong>[A3a/A3b]</strong> Reframed the deprivation finding around the unmeasured-need vs genuine-access question, with a direct morbidity-by-deprivation check.</li>
<li><strong>[A4/A4b]</strong> New funnel plot of case-mix-adjusted admission rates, with a completeness diagnostic showing the outlier signal is a recording-definition issue, not an admission-practice one.</li>
<li><strong>[A2]</strong> New test for trusts where Black admission is significantly lower than White.</li>
<li><strong>[K4]</strong> New broad MBRRACE-comparable ethnicity grouping presented alongside the detailed one.</li>
<li><strong>[A5c]</strong> New exploratory ethnicity × deprivation interaction: no evidence of a steeper deprivation penalty for minority groups.</li>
<li><strong>[A5a]</strong> New length-of-stay analysis: the crude Black excess is entirely case-mix; Pakistani and Bangladeshi babies stay longer than expected.</li>
<li><strong>[A5b]</strong> New descriptive mortality section: the Pakistani excess is not explained by gestational mix; the Black excess mostly is.</li>
<li><strong>Editorial pass (July 2026):</strong> tightened prose, fixed a stray inconsistency in the Chinese-group explanation count (now three, consistently), and reduced formatting noise.</li>
<li><strong>Restructuring (July 2026):</strong> this report was split into a short Findings report (this document) and a new <a href="technical_appendix.html">Technical Appendix</a> containing full methodology, model specifications, and diagnostic detail. Nothing was deleted — every number here can be traced to the appendix. This was done because the combined report had grown too long and technical for a policy audience; splitting it keeps the findings readable without losing any of the underlying rigor.</li>
</ul>
<p><em>(This box is temporary review scaffolding and will be removed before final publication.)</em></p>
</div>
</div>
<section id="executive-summary" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Executive Summary</h1>
<p>This report examines whether, after accounting for clinical need, access to neonatal critical care (NCC) differs by ethnicity or deprivation, using around 476,000 English hospital births in 2023/24. The analysis uses hierarchical logistic regression: a primary model adjusting for gestation, a sensitivity model additionally adjusting for birth weight and Apgar score, and a baseline admission rate for each delivery trust. Full methodology and every diagnostic check behind these numbers are in the <a href="technical_appendix.html">Technical Appendix</a>.</p>
<section id="key-messages" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="key-messages"><span class="header-section-number">1.1</span> Key Messages</h2>
<ol type="1">
<li><p>Clinical need drives admission. Each additional week of gestation reduces the odds of NCC admission by around 38%; ethnicity and deprivation effects are small by comparison. On its central question, the system appears need-led.</p></li>
<li><p>There is no evidence of under-admission for Black babies at national level. Odds ratios are approximately 1.04 in both the primary and sensitivity models — essentially parity with White British, despite higher average clinical need. This is a finding about admission rates only, not about the wider quality of care received.</p></li>
<li><p>Two groups warrant follow-up. Pakistani babies’ lower odds in the primary model move to near-parity once birth weight and Apgar are added, so are largely explained by clinical case-mix — and the <a href="technical_appendix.html#length-of-stay">length-of-stay and mortality</a> analyses show the same pattern, consistent with these babies being admitted only once more seriously unwell. Chinese babies show around 24% lower odds even after adjustment; three broad explanations are consistent with this and the data cannot separate them (see <a href="#ethnicity">Ethnicity</a>).</p></li>
<li><p>The deprivation gradient is consistent with need rather than over-admission. Odds are around 9% higher for the most deprived quintile relative to the least, stable after clinical adjustment, and a <a href="technical_appendix.html#imd-morbidity">direct morbidity check</a> shows clinical need itself rising with deprivation in ways the model does not capture.</p></li>
<li><p>Between-trust variation is the largest residual signal (ICC around 32%), but it bundles admission practice with recording practice and cannot be read at face value. The <a href="technical_appendix.html#outlier-completeness">funnel-outlier diagnostic</a> shows the most extreme trusts record NCC for 21–40% of their term babies, against roughly 7% nationally — a recording signature, not an admission-practice one. Standardising what counts as an NCC day in PbR-CC returns is the highest-value data improvement identified by this work.</p></li>
<li><p>These results address whether a baby is admitted, not when. The planned Phase 2 analysis of admission timing is on hold pending access to a data environment with a usable date of birth.</p></li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Terms used in this report
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><strong>Odds ratio (OR)</strong>: how much more, or less, likely a group is to be admitted than the reference group, after adjustment. OR 1.00 = parity; OR 1.10 = 10% higher odds; OR 0.90 = 10% lower odds.</li>
<li><strong>ICC (intraclass correlation)</strong>: the share of variation in admission that sits between hospitals rather than between babies.</li>
<li><strong>BH-adjusted p-value</strong>: a p-value corrected for testing several groups at once, so that chance findings among (for example) 9 ethnicity groups aren’t over-interpreted.</li>
<li><strong>O/E ratio</strong>: observed cases (deaths or admissions) divided by the number expected given a group’s clinical profile. Above 1 means more than expected; below 1 means fewer.</li>
<li><strong>Rate ratio (RR)</strong>: the same idea as an odds ratio, applied to a count outcome (e.g.&nbsp;days of care) rather than a yes/no one.</li>
</ul>
</div>
</div>
<hr>
</section>
</section>
<section id="methods-in-brief" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Methods, in brief</h1>
<p>The primary model is a hierarchical (mixed-effects) logistic regression — <code>NCC_Admitted ~ Gestation + Ethnicity + IMD</code>, with a random intercept per delivery trust — fit on 476,475 hospital births in England in FY 2023/24 with complete data on these fields. A sensitivity model adds birth weight and Apgar 5-minute score, on the 218,886 births (45.9%) where these are also complete.</p>
<p>The random intercept means every comparison is effectively <em>within</em> the same hospital: the estimates answer, for two clinically similar babies born at the same trust, whether the chance of admission differs by ethnicity or deprivation. Ethnicity is coded using nine disaggregated NHS categories rather than broad groups, because — as the results below show — broad grouping conceals real differences between, for example, Pakistani, Indian and Bangladeshi babies. Deprivation uses 2015-vintage IMD quintiles of the mother’s recorded address.</p>
<p>Full methodology — the causal reasoning behind variable selection, cohort filters, model equations, and why clustering is at trust rather than site level — is in the <a href="technical_appendix.html#methods">Technical Appendix</a>.</p>
<hr>
</section>
<section id="results" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Results</h1>
<section id="clinical-factors" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="clinical-factors"><span class="header-section-number">3.1</span> Clinical Factors</h2>
<p>Gestation is by far the strongest predictor of NCC admission: each additional week reduces the odds by around 38%. This confirms the model is capturing genuine clinical need, and it is the backdrop against which the ethnicity and deprivation effects below — much smaller in comparison — should be read. Full fixed-effects table in the <a href="technical_appendix.html#model-2-mixed-effects-logistic-regression">Technical Appendix</a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-forest" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-forest-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="modelling_results_files/figure-html/fig-forest-1.png" class="img-fluid figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-forest-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Odds ratios for NCC admission by ethnicity and deprivation (adjusted for gestation, with hospital random effects)
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="ethnicity" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="ethnicity"><span class="header-section-number">3.2</span> Ethnicity</h2>
<p>Most ethnic groups sit within a few percent of parity with White British babies. The Black group sits at near-exact parity; Pakistani and Chinese babies sit below parity; Indian and Bangladeshi babies sit slightly above. How each estimate responds when birth weight and Apgar are added (the sensitivity model) is the key to interpreting them:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 22%">
<col style="width: 32%">
<col style="width: 32%">
</colgroup>
<thead>
<tr class="header">
<th>Group</th>
<th>Primary OR</th>
<th>Sensitivity OR</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Pakistani</td>
<td>0.89</td>
<td>0.97</td>
<td>Moves towards parity — clinical factors explain much of the difference</td>
</tr>
<tr class="even">
<td>Chinese</td>
<td>0.70</td>
<td>0.76</td>
<td>Still notably lower, at the boundary of nominal significance in the smaller sample</td>
</tr>
<tr class="odd">
<td>Indian</td>
<td>1.05</td>
<td>1.16</td>
<td>Increases further — higher access after clinical adjustment</td>
</tr>
<tr class="even">
<td>Bangladeshi</td>
<td>1.06</td>
<td>1.17</td>
<td>Similar pattern to Indian</td>
</tr>
<tr class="odd">
<td>Black</td>
<td>1.04</td>
<td>1.04</td>
<td>Stable — consistent with equitable access</td>
</tr>
</tbody>
</table>
<p>The differences among Indian, Pakistani and Bangladeshi babies after adjustment are the clearest demonstration of why this report uses disaggregated ethnicity coding, rather than the broader groups MBRRACE-style reporting typically uses — a broader grouping gives a reassuring headline (no broad group far from parity) but conceals this spread and the Chinese finding below (full comparison in the <a href="technical_appendix.html#broad-ethnicity">Technical Appendix</a>).</p>
<p>Black babies sit at national parity (OR 1.04, stable after adjustment) despite carrying higher average clinical need on average — no evidence of national under-admission. One of the 92 trusts with enough Black births to test showed a significantly lower rate and has been flagged for a case-mix-standardised follow-up (full test in the <a href="technical_appendix.html#black-underaccess-screen">Technical Appendix</a>).</p>
<p>Chinese babies show the largest unexplained gap: around 24% lower adjusted odds. Three broad explanations are consistent with this and the data cannot separate them — unmeasured clinical need, a smaller and less stable sample, or data/access factors (differences in care-seeking, or possible under-recording). This is a question for follow-up, not a conclusion (see <a href="#recommendations">Recommendations</a> and the <a href="technical_appendix.html#ethnicity">Technical Appendix</a> for detail).</p>
</section>
<section id="deprivation" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="deprivation"><span class="header-section-number">3.3</span> Deprivation</h2>
<p>Babies from the most deprived quintile have 2% higher odds of NCC admission than the least deprived, stepping up consistently across quintiles. This could mean the model is picking up genuine clinical need that correlates with deprivation but isn’t fully captured by gestation, birth weight and Apgar alone — or it could mean a genuine difference in admission threshold. The two are hard to tell apart from the model alone.</p>
<p>A direct check of morbidity by deprivation quintile supports the first reading: every marker of clinical need (preterm birth, very preterm birth, low birth weight) rises monotonically with deprivation, and low birth weight among <em>term</em> babies alone very nearly doubles from least to most deprived (full quintile table in the <a href="technical_appendix.html#imd-morbidity">Technical Appendix</a>). We also checked whether deprivation carries a steeper penalty for any one ethnic group — it doesn’t appear to, though the data for smaller ethnic groups are too thin to be confident either way (technical detail in the <a href="technical_appendix.html#eth-imd-interaction">Appendix</a>).</p>
</section>
<section id="hospital-variation" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="hospital-variation"><span class="header-section-number">3.4</span> Hospital Variation</h2>
<p>Once gestation, ethnicity and deprivation are accounted for, the trust a baby is born in is the largest remaining source of variation in the model — an ICC of around 32%. This bundles together genuine differences in clinical practice, referral patterns, and how providers record NCC activity, and should not be read as a clean measure of admission practice alone (full breakdown of what it can and can’t mean in the <a href="technical_appendix.html#hospital-variation">Technical Appendix</a>).</p>
<p>The funnel plot below checks each trust’s case-mix-adjusted admission rate against control limits; a small number of trusts sit well outside them.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-funnel" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-funnel-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="modelling_results_files/figure-html/fig-funnel-1.png" class="img-fluid figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-funnel-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Funnel plot of case-mix-adjusted NCC admission rates by delivery trust. Points outside the 99.8% limits admit at a rate that case-mix and chance alone do not explain. Adjusted for gestation, ethnicity and IMD via the primary model’s fixed effects (trust random effect removed).
</figcaption>
</figure>
</div>
</div>
</div>
<p>Looking closely at the trusts outside the limits, the evidence points to a recording issue rather than a practice one: they record NCC for 21–40% of <em>term</em> babies, against ~7% nationally, most likely because they count a broader range of neonatal unit activity as “NCC” days in their PbR-CC returns than their peers do (full diagnostic, which rules out missing records and missing fields as alternative explanations, in the <a href="technical_appendix.html#outlier-completeness">Technical Appendix</a>). Standardising what counts as an NCC day is the single highest-value data improvement this analysis points to (Recommendation 1).</p>
</section>
<section id="length-of-stay-and-mortality" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="length-of-stay-and-mortality"><span class="header-section-number">3.5</span> Length of Stay and Mortality</h2>
<p>Two further checks ask not just who is admitted, but what happens next.</p>
<p><strong>Length of stay.</strong> Among admitted babies, the crude excess stay length for Black babies disappears entirely once adjusted for gestation (RR 0.98 (0.95–1.01)) — babies are admitted at parity <em>and</em> receive the expected amount of care once admitted. Pakistani babies stay around 9% longer than expected for their gestation (RR 1.09 (1.05–1.12)), alongside their lower admission odds — a pattern consistent with a higher effective admission threshold, though this data cannot fully separate that from greater within-gestation morbidity (full model in the <a href="technical_appendix.html#length-of-stay">Technical Appendix</a>).</p>
<p><strong>Mortality.</strong> A descriptive, dual-source mortality flag — not a substitute for MBRRACE’s linked-registration data, and read with heavy ascertainment caveats — shows the Black crude excess is mostly explained by gestational mix, but the Pakistani excess is not: 80% more recorded deaths than the group’s gestational profile predicts. Combined with the admission and length-of-stay findings, this points to the same follow-up: severity at the point of admission (Recommendation 6). Full detail, including why this flag is not a substitute for national mortality statistics, is in the <a href="technical_appendix.html#mortality">Technical Appendix</a>.</p>
<hr>
</section>
</section>
<section id="recommendations" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Recommendations</h1>
<p>The analysis is reassuring on its headline question — no signal of national under-admission for Black babies — but it surfaces concrete follow-ups. In rough priority order:</p>
<ol type="1">
<li><p>Standardise what counts as an “NCC day” in PbR-CC returns. The <a href="technical_appendix.html#outlier-completeness">funnel diagnostic</a> shows the most extreme provider variation is recording breadth, not admission practice: outlier trusts record NCC for 21–40% of their term babies against ~7% nationally. A tighter definition — or an audit of the outlier trusts’ returns — would sharpen every downstream use of this data, including the ICC and any future benchmarking.</p></li>
<li><p>Improve completeness of birth weight and Apgar in MSDS. Jointly complete for under half the cohort, this is the single biggest constraint on case-mix adjustment — it is why the primary model must lean on gestation alone.</p></li>
<li><p>Follow up the one trust flagged for lower Black admission (identity held internally) with a case-mix-standardised check — a per-trust Black observed/expected ratio — before drawing any conclusion about access.</p></li>
<li><p>Investigate the Chinese-group gap. Around 24% lower adjusted odds with three candidate explanations this data cannot separate; richer clinical covariates or direct provider engagement would be needed to distinguish unmeasured need from sample-size instability or from access/recording factors.</p></li>
<li><p>Extend to outcomes and timing. Length of stay and a descriptive mortality look are analysed in the <a href="technical_appendix.html">Technical Appendix</a> (<a href="technical_appendix.html#length-of-stay">stay length</a>, <a href="technical_appendix.html#mortality">mortality</a>) — both add Pakistani findings that sharpen the case for the Phase 2 timing analysis once the day-of-birth data environment is available. A definitive mortality analysis needs linked death registrations (MBRRACE territory), not this extract.</p></li>
<li><p>Follow up the Pakistani stay-length excess. Fewer admissions plus longer stays once admitted is consistent with a higher effective admission threshold, but equally with greater within-gestation morbidity; distinguishing them needs severity-at-admission data (care level at day 1, organ support) — a planned extension.</p></li>
</ol>
</section>
<section id="limitations" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Limitations</h1>
<ol type="1">
<li><p>Clinical covariate completeness: Birth weight is recorded for ~46% of births and Apgar for ~79%; jointly they limit the sensitivity model to under half the cohort. The primary model uses gestation alone to preserve sample size.</p></li>
<li><p>Single year of data: Results may not generalise to other time periods.</p></li>
<li><p>Residual confounding: While ethnicity is now disaggregated (e.g., Indian, Pakistani, Bangladeshi separately), within-group heterogeneity remains. Black ethnicities are still grouped together in the model.</p></li>
<li><p>Selection bias: Analysis restricted to births with complete data on gestation, ethnicity, IMD and delivery trust — though the retained share is high and similar across providers (see the <a href="technical_appendix.html#outlier-completeness">funnel diagnostic</a>).</p></li>
<li><p>Outcome definition: “NCC admission” is whatever providers record as NCC in two administrative sources, and the funnel diagnostic shows the breadth of that recording varies materially between providers. The outcome is best read as “received care recorded as NCC”, not “occupied a critical care cot”.</p></li>
</ol>
<hr>
<p>Full technical detail — model specifications, causal reasoning behind variable selection, and every diagnostic check behind the numbers above — is in the <a href="technical_appendix.html">Technical Appendix</a>.</p>
<p>Report generated: 2026-07-21 14:54:11.308447</p>
<p>R version: R version 4.6.1 (2026-06-24 ucrt)</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>