<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ashley Dickson">
<meta name="dcterms.date" content="2026-07-21">

<title>Inequalities in Access to Neonatal Critical Care: Phase 1 Technical Appendix – NCC Inequalities Analysis</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-6b423f165eeea3787de40cb4f8e821c3.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>

<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">


  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">NCC Inequalities Analysis</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Overview</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./modelling_results.html"> 
<span class="menu-text">Phase 1: Findings</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./technical_appendix.html" aria-current="page"> 
<span class="menu-text">Phase 1: Technical Appendix</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#methods" id="toc-methods" class="nav-link active" data-scroll-target="#methods"><span class="header-section-number">1</span> Methods</a>
  <ul class="collapse">
  <li><a href="#study-population" id="toc-study-population" class="nav-link" data-scroll-target="#study-population"><span class="header-section-number">1.1</span> Study Population</a></li>
  <li><a href="#outcome-definition-ncc_admitted" id="toc-outcome-definition-ncc_admitted" class="nav-link" data-scroll-target="#outcome-definition-ncc_admitted"><span class="header-section-number">1.2</span> Outcome definition (<code>NCC_Admitted</code>)</a></li>
  <li><a href="#cohort-filter-and-deprivation-vintage" id="toc-cohort-filter-and-deprivation-vintage" class="nav-link" data-scroll-target="#cohort-filter-and-deprivation-vintage"><span class="header-section-number">1.3</span> Cohort filter and deprivation vintage</a></li>
  <li><a href="#variable-selection" id="toc-variable-selection" class="nav-link" data-scroll-target="#variable-selection"><span class="header-section-number">1.4</span> Variable selection</a>
  <ul class="collapse">
  <li><a href="#why-selection-is-not-data-driven-stepwise-lasso" id="toc-why-selection-is-not-data-driven-stepwise-lasso" class="nav-link" data-scroll-target="#why-selection-is-not-data-driven-stepwise-lasso"><span class="header-section-number">1.4.1</span> Why selection is not data-driven (stepwise / LASSO)</a></li>
  <li><a href="#candidate-variables-considered" id="toc-candidate-variables-considered" class="nav-link" data-scroll-target="#candidate-variables-considered"><span class="header-section-number">1.4.2</span> Candidate variables considered</a></li>
  </ul></li>
  <li><a href="#statistical-approach" id="toc-statistical-approach" class="nav-link" data-scroll-target="#statistical-approach"><span class="header-section-number">1.5</span> Statistical Approach</a></li>
  <li><a href="#birth-weight-data-source" id="toc-birth-weight-data-source" class="nav-link" data-scroll-target="#birth-weight-data-source"><span class="header-section-number">1.6</span> Birth Weight Data Source</a></li>
  <li><a href="#random-effect-grouping" id="toc-random-effect-grouping" class="nav-link" data-scroll-target="#random-effect-grouping"><span class="header-section-number">1.7</span> Random-effect Grouping</a>
  <ul class="collapse">
  <li><a href="#why-mixed-effects" id="toc-why-mixed-effects" class="nav-link" data-scroll-target="#why-mixed-effects"><span class="header-section-number">1.7.1</span> Why mixed effects?</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results"><span class="header-section-number">2</span> Results</a>
  <ul class="collapse">
  <li><a href="#model-2-mixed-effects-logistic-regression" id="toc-model-2-mixed-effects-logistic-regression" class="nav-link" data-scroll-target="#model-2-mixed-effects-logistic-regression"><span class="header-section-number">2.1</span> Model 2: Mixed Effects Logistic Regression</a>
  <ul class="collapse">
  <li><a href="#fixed-effects-odds-ratios" id="toc-fixed-effects-odds-ratios" class="nav-link" data-scroll-target="#fixed-effects-odds-ratios"><span class="header-section-number">2.1.1</span> Fixed Effects (Odds Ratios)</a></li>
  <li><a href="#forest-plot-ethnicity-and-deprivation" id="toc-forest-plot-ethnicity-and-deprivation" class="nav-link" data-scroll-target="#forest-plot-ethnicity-and-deprivation"><span class="header-section-number">2.1.2</span> Forest Plot: Ethnicity and Deprivation</a></li>
  <li><a href="#random-effects-hospital-variation" id="toc-random-effects-hospital-variation" class="nav-link" data-scroll-target="#random-effects-hospital-variation"><span class="header-section-number">2.1.3</span> Random Effects: Hospital Variation</a></li>
  <li><a href="#funnel-plot-case-mix-adjusted-admission-rates" id="toc-funnel-plot-case-mix-adjusted-admission-rates" class="nav-link" data-scroll-target="#funnel-plot-case-mix-adjusted-admission-rates"><span class="header-section-number">2.1.4</span> Funnel Plot: Case-mix-adjusted Admission Rates</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#interpretation" id="toc-interpretation" class="nav-link" data-scroll-target="#interpretation"><span class="header-section-number">3</span> Interpretation</a>
  <ul class="collapse">
  <li><a href="#clinical-factors" id="toc-clinical-factors" class="nav-link" data-scroll-target="#clinical-factors"><span class="header-section-number">3.1</span> Clinical Factors</a></li>
  <li><a href="#ethnicity" id="toc-ethnicity" class="nav-link" data-scroll-target="#ethnicity"><span class="header-section-number">3.2</span> Ethnicity</a>
  <ul class="collapse">
  <li><a href="#broad-ethnicity" id="toc-broad-ethnicity" class="nav-link" data-scroll-target="#broad-ethnicity"><span class="header-section-number">3.2.1</span> A broad, MBRRACE-comparable grouping</a></li>
  </ul></li>
  <li><a href="#focus-black-ethnicity-and-the-maternity-review-context" id="toc-focus-black-ethnicity-and-the-maternity-review-context" class="nav-link" data-scroll-target="#focus-black-ethnicity-and-the-maternity-review-context"><span class="header-section-number">3.3</span> Focus: Black Ethnicity and the Maternity Review Context</a>
  <ul class="collapse">
  <li><a href="#raw-ncc-admission-rates" id="toc-raw-ncc-admission-rates" class="nav-link" data-scroll-target="#raw-ncc-admission-rates"><span class="header-section-number">3.3.1</span> Raw NCC Admission Rates</a></li>
  <li><a href="#clinical-context-higher-need-equitable-access" id="toc-clinical-context-higher-need-equitable-access" class="nav-link" data-scroll-target="#clinical-context-higher-need-equitable-access"><span class="header-section-number">3.3.2</span> Clinical Context: Higher Need, Equitable Access</a></li>
  <li><a href="#hospital-level-variation" id="toc-hospital-level-variation" class="nav-link" data-scroll-target="#hospital-level-variation"><span class="header-section-number">3.3.3</span> Hospital-Level Variation</a></li>
  <li><a href="#black-underaccess-screen" id="toc-black-underaccess-screen" class="nav-link" data-scroll-target="#black-underaccess-screen"><span class="header-section-number">3.3.4</span> Trust-level screen for lower Black admission rates</a></li>
  </ul></li>
  <li><a href="#deprivation" id="toc-deprivation" class="nav-link" data-scroll-target="#deprivation"><span class="header-section-number">3.4</span> Deprivation</a>
  <ul class="collapse">
  <li><a href="#imd-morbidity" id="toc-imd-morbidity" class="nav-link" data-scroll-target="#imd-morbidity"><span class="header-section-number">3.4.1</span> A direct check: morbidity by deprivation quintile</a></li>
  <li><a href="#eth-imd-interaction" id="toc-eth-imd-interaction" class="nav-link" data-scroll-target="#eth-imd-interaction"><span class="header-section-number">3.4.2</span> Does the deprivation gradient differ by ethnic group?</a></li>
  </ul></li>
  <li><a href="#hospital-variation" id="toc-hospital-variation" class="nav-link" data-scroll-target="#hospital-variation"><span class="header-section-number">3.5</span> Hospital Variation</a></li>
  </ul></li>
  <li><a href="#sensitivity-analysis-full-clinical-adjustment" id="toc-sensitivity-analysis-full-clinical-adjustment" class="nav-link" data-scroll-target="#sensitivity-analysis-full-clinical-adjustment"><span class="header-section-number">4</span> Sensitivity Analysis: Full Clinical Adjustment</a>
  <ul class="collapse">
  <li><a href="#comparing-primary-and-sensitivity-models" id="toc-comparing-primary-and-sensitivity-models" class="nav-link" data-scroll-target="#comparing-primary-and-sensitivity-models"><span class="header-section-number">4.1</span> Comparing Primary and Sensitivity Models</a></li>
  </ul></li>
  <li><a href="#length-of-stay" id="toc-length-of-stay" class="nav-link" data-scroll-target="#length-of-stay"><span class="header-section-number">5</span> Length of Stay Among Admitted Babies</a>
  <ul class="collapse">
  <li><a href="#what-adjustment-does-to-the-crude-picture" id="toc-what-adjustment-does-to-the-crude-picture" class="nav-link" data-scroll-target="#what-adjustment-does-to-the-crude-picture"><span class="header-section-number">5.1</span> What adjustment does to the crude picture</a></li>
  </ul></li>
  <li><a href="#mortality" id="toc-mortality" class="nav-link" data-scroll-target="#mortality"><span class="header-section-number">6</span> Mortality Among Live Births: A Descriptive Look</a>
  <ul class="collapse">
  <li><a href="#measuring-death-in-this-data" id="toc-measuring-death-in-this-data" class="nav-link" data-scroll-target="#measuring-death-in-this-data"><span class="header-section-number">6.1</span> Measuring death in this data</a></li>
  <li><a href="#crude-rates-and-gestation-standardised-ratios" id="toc-crude-rates-and-gestation-standardised-ratios" class="nav-link" data-scroll-target="#crude-rates-and-gestation-standardised-ratios"><span class="header-section-number">6.2</span> Crude rates and gestation-standardised ratios</a></li>
  <li><a href="#what-standardisation-does-to-the-crude-picture" id="toc-what-standardisation-does-to-the-crude-picture" class="nav-link" data-scroll-target="#what-standardisation-does-to-the-crude-picture"><span class="header-section-number">6.3</span> What standardisation does to the crude picture</a></li>
  </ul></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations"><span class="header-section-number">7</span> Limitations</a></li>
  <li><a href="#technical-details" id="toc-technical-details" class="nav-link" data-scroll-target="#technical-details"><span class="header-section-number">8</span> Technical Details</a></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Inequalities in Access to Neonatal Critical Care: Phase 1 Technical Appendix</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Ashley Dickson </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 21, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>About this appendix
</div>
</div>
<div class="callout-body-container callout-body">
<p>This document contains the full methodology, model specifications, and diagnostic checks behind the Phase 1 analysis of NCC access. For headline results, key messages, and recommendations, see the <a href="modelling_results.html">Findings report</a> — this appendix exists so every number and modelling choice in that report can be checked and reproduced. Section numbers here are independent of the Findings report.</p>
<p><em>(This box, like the one in the Findings report, is temporary review scaffolding and will be removed before final publication.)</em></p>
</div>
</div>
<section id="methods" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Methods</h1>
<section id="study-population" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="study-population"><span class="header-section-number">1.1</span> Study Population</h2>
<p>Primary analysis: 476,475 hospital births in England during financial year 2023/24 with complete data on NCC admission, gestation, ethnicity, IMD quintile, and delivery trust.</p>
<p>Sensitivity analysis: 218,886 births (45.9% of primary sample) with additional complete data on birth weight and Apgar 5-minute score.</p>
<p>The cohort is defined by <em>birth</em> in 2023/24, not by NCC activity in 2023/24. Babies enter on the basis of their MSDS birth record (the financial year is derived from year and month of birth); a baby born before April 2023 who continued a neonatal stay into the study year is <em>not</em> included. Critical-care linkage then looks outward from each birth — and is permitted to reach about 30 days into 2024/25 — so that NCC admissions for babies born late in March 2024 are not under-counted; but the linkage never pulls earlier-born babies into the cohort.</p>
</section>
<section id="outcome-definition-ncc_admitted" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="outcome-definition-ncc_admitted"><span class="header-section-number">1.2</span> Outcome definition (<code>NCC_Admitted</code>)</h2>
<p>The outcome flags whether a baby has <em>care recorded as Neonatal Critical Care</em> in either of the two available administrative sources: MSDS MSD402 (provider-submitted neonatal admission records) or PbR-CC (the Payment-by-Results critical-care daily extract, filtered to <code>CC_Type = 'NCC'</code>). A baby is <code>NCC_Admitted = 1</code> if they appear in either source. The two sources do not agree perfectly: the CC source records roughly 3.8 times more NCC admissions than MSDS alone, and submission completeness for both sources varies between providers. The outcome should therefore be read as “received care recorded as NCC” rather than a clinical judgement that a baby needed a critical-care cot.</p>
</section>
<section id="cohort-filter-and-deprivation-vintage" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="cohort-filter-and-deprivation-vintage"><span class="header-section-number">1.3</span> Cohort filter and deprivation vintage</h2>
<p>Two further constraints apply to the primary cohort:</p>
<ul>
<li><em>Hospital births only.</em> The cohort is restricted to babies whose mother has a recorded MSD301 hospital labour-delivery spell (<code>Mother_Admission_Date IS NOT NULL</code>). This is consistent with the study’s “hospital births in England” frame, but it excludes home births and any births where the labour record did not link in MSDS — the latter is not random across providers.</li>
<li><em>IMD 2015 vintage.</em> The deprivation field used (<code>IMD_Decile_2015</code>) is derived from the 2015 release of the English Indices of Deprivation. IMD 2019 is now the current vintage, and a 2025 release is anticipated. Some areas have reclassified noticeably since 2015. Findings should be interpreted as applying to the 2015 deprivation classification of the mother’s recorded address.</li>
</ul>
</section>
<section id="variable-selection" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="variable-selection"><span class="header-section-number">1.4</span> Variable selection</h2>
<p>This is a causal estimation problem rather than a prediction problem, and that distinction governs the approach to selecting variables. The aim is not to predict NCC admission as accurately as possible; it is to estimate the association of ethnicity and deprivation with admission conditional on clinical need. Each candidate variable is therefore judged first on its causal role, and only then on whether it is usable:</p>
<ul>
<li>Causal role. A variable is an exposure of interest (ethnicity, IMD — the inequalities being measured), a confounder of need (clinical case-mix that must be adjusted for so that “conditional on need” is meaningful), a mediator (on the causal pathway from exposure to admission, which must not be adjusted for if the total effect is wanted — the “Table 2 fallacy”), or a collider (adjusting for which would introduce bias). Confounders are candidates for adjustment; mediators and colliders are left out, however predictive they are.</li>
<li>Clinical relevance. Among confounders, how strongly the variable drives genuine NCC need.</li>
<li>Completeness. Whether it is recorded for enough of the cohort to use without shrinking or biasing the sample. A near-complete weak confounder can be preferable to a strong but half-missing one — the gestation-versus-birth-weight trade-off below.</li>
<li>Collinearity. Correlation among the adjustment variables inflates the variance of those coefficients, but does not bias the ethnicity/IMD estimates unless a covariate is collinear with ethnicity or IMD. Correlated clinical measures are a reason for parsimony, not a threat to the headline estimates.</li>
</ul>
<section id="why-selection-is-not-data-driven-stepwise-lasso" class="level3" data-number="1.4.1">
<h3 data-number="1.4.1" class="anchored" data-anchor-id="why-selection-is-not-data-driven-stepwise-lasso"><span class="header-section-number">1.4.1</span> Why selection is not data-driven (stepwise / LASSO)</h3>
<p>Algorithmic selection — stepwise regression, LASSO, and similar — optimises <em>predictive fit</em> and is blind to causal role. Such a procedure would happily adjust for a mediator (biasing the exposure estimate toward the null), or drop a true confounder because it is collinear with another. For a causal access question this is the wrong tool: it answers “what predicts admission?” when we are asking “is admission equitable conditional on need?”. Selection here is therefore <em>pre-specified on clinical and causal grounds</em> by design. Where robustness to the adjustment set matters, the appropriate check is not a data-driven search but a small set of pre-specified alternative specifications (see <a href="modelling_results.html#recommendations">Recommendations</a> in the Findings report).</p>
</section>
<section id="candidate-variables-considered" class="level3" data-number="1.4.2">
<h3 data-number="1.4.2" class="anchored" data-anchor-id="candidate-variables-considered"><span class="header-section-number">1.4.2</span> Candidate variables considered</h3>
<p>Every variable considered for the model was judged first on its causal role (confounder, exposure, mediator, or collider) and only then on whether it was usable. The full table — each variable, its likely role, whether it’s in the current data extract, and the resulting decision — is below.</p>
<p>“In extract?” distinguishes additions that are available now from those that would need a dataset rebuild.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Variable</th>
<th>Likely role</th>
<th style="text-align: center;">In extract?</th>
<th>Decision and rationale</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Gestational age</td>
<td>Confounder (need)</td>
<td style="text-align: center;">Yes</td>
<td>In, primary. Dominant driver of need; recorded for almost every birth, so it anchors the model on the full sample.</td>
</tr>
<tr class="even">
<td>Birth weight</td>
<td>Confounder (need)</td>
<td style="text-align: center;">Yes</td>
<td>In, sensitivity only. Adds genuine signal beyond gestation (small-for-gestational-age), but only ~46% complete; confined to the sensitivity model to avoid shrinking the primary sample.</td>
</tr>
<tr class="odd">
<td>Apgar (5-min)</td>
<td>Confounder (need)</td>
<td style="text-align: center;">Yes</td>
<td>In, sensitivity only. Captures acute intrapartum compromise — a partly distinct axis from prematurity. Same completeness constraint as birth weight.</td>
</tr>
<tr class="even">
<td>Apgar (1-min)</td>
<td>Confounder (need)</td>
<td style="text-align: center;">Yes</td>
<td>Excluded. Very highly collinear with the 5-minute score, which is the more prognostic and standard measure; little marginal information.</td>
</tr>
<tr class="odd">
<td>Baby sex</td>
<td>Confounder (weak)</td>
<td style="text-align: center;">Yes</td>
<td>Candidate to add now. Males carry modestly higher risk; near-complete. Cheap robustness addition; unlikely to move the headline estimates.</td>
</tr>
<tr class="even">
<td>Birth order / plurality</td>
<td>Confounder (need)</td>
<td style="text-align: center;">Yes (<code>Birth_Order</code>)</td>
<td>Candidate to add now. Multiple births are a major driver of prematurity with different ethnicity/deprivation distributions; worth testing as a covariate.</td>
</tr>
<tr class="odd">
<td>Unit type (NICU / LNU / SCBU)</td>
<td>Structural confounder</td>
<td style="text-align: center;">Derivable</td>
<td>Candidate to add now. Admission probability depends heavily on whether the baby was <em>born</em> in a unit with tertiary cots. Currently absorbed into the trust random effect; could be made explicit via the NNAP unit mapping.</td>
</tr>
<tr class="even">
<td>Delivery method</td>
<td>Mediator / collider</td>
<td style="text-align: center;">Yes</td>
<td>Excluded by design. Plausibly downstream of fetal compromise (compromise → emergency caesarean → NCC); adjusting for it would bias the access estimate.</td>
</tr>
<tr class="odd">
<td>Complex social factors / employment / disability (at booking)</td>
<td>Part of the exposure construct</td>
<td style="text-align: center;">Yes</td>
<td>Excluded by design. Arguably components of the deprivation/inequality construct rather than confounders; adjusting for them could regress away part of the very inequality being measured.</td>
</tr>
<tr class="even">
<td>Smoking at booking (CQIM)</td>
<td>Confounder, partly mediator of IMD</td>
<td style="text-align: center;">No — rebuild</td>
<td>Future. Strong driver of growth restriction and preterm birth, but correlated with deprivation, so partly <em>on</em> the IMD pathway. A natural addition; needs extraction.</td>
</tr>
<tr class="odd">
<td>Maternal BMI / parity</td>
<td>Confounder (need)</td>
<td style="text-align: center;">No — rebuild</td>
<td>Future. Plausible upstream confounders; need extraction.</td>
</tr>
<tr class="even">
<td>Maternal age</td>
<td>Confounder (need)</td>
<td style="text-align: center;">No — blocked</td>
<td>Future. U-shaped risk and a confounder for both exposures, but the source date-of-birth field is missing in this environment.</td>
</tr>
<tr class="odd">
<td>Gestational diabetes / hypertension / pre-eclampsia</td>
<td>Confounder (need)</td>
<td style="text-align: center;">No — rebuild</td>
<td>Future. Drive prematurity and NCC need; need extraction.</td>
</tr>
<tr class="even">
<td>Postpartum haemorrhage (CQIM)</td>
<td>Maternal outcome (not a clean confounder)</td>
<td style="text-align: center;">No — rebuild</td>
<td>Future, descriptive only. A maternal <em>intrapartum</em> outcome largely downstream of the determinants of the baby’s need; its link to <em>neonatal</em> CC is weak and via shared causes. Worth a descriptive look, but not a case-mix adjustment.</td>
</tr>
<tr class="odd">
<td>Congenital anomaly</td>
<td>Confounder / part-outcome</td>
<td style="text-align: center;">No — rebuild</td>
<td>Future, with caution. A strong driver of admission, but MSDS ascertainment is poor and it is arguably part outcome rather than pure case-mix.</td>
</tr>
<tr class="even">
<td>Ethnicity (disaggregated)</td>
<td>Exposure</td>
<td style="text-align: center;">Yes</td>
<td>In. The granularity itself is a finding (within-Asian heterogeneity). A <a href="#broad-ethnicity">broad MBRRACE-style grouping</a> is presented alongside for comparability and small-number stability.</td>
</tr>
<tr class="odd">
<td>IMD quintile</td>
<td>Exposure</td>
<td style="text-align: center;">Yes</td>
<td>In. Area-level deprivation of the mother’s recorded address (2015 vintage; see above).</td>
</tr>
<tr class="even">
<td>Delivery trust</td>
<td>Random effect</td>
<td style="text-align: center;">Yes</td>
<td>In. Random intercept; see <em>Random-effect Grouping</em>.</td>
</tr>
</tbody>
</table>
<p>In short, the primary model deliberately carries the need signal on gestation alone — the one near-complete clinical confounder — adds the two exposures of interest, and leaves the trust structure to the random intercept. The sensitivity model adds birth weight and Apgar where they are observed. The remaining candidates are excluded either <em>by causal role</em> (mediators, colliders, and components of the exposure construct) or <em>by data availability</em> (factors awaiting a dataset rebuild), and are picked up as future work rather than omitted for convenience.</p>
</section>
</section>
<section id="statistical-approach" class="level2" data-number="1.5">
<h2 data-number="1.5" class="anchored" data-anchor-id="statistical-approach"><span class="header-section-number">1.5</span> Statistical Approach</h2>
<p>We fitted three models:</p>
<ol type="1">
<li><p>Model 1 (Fixed effects only): Standard logistic regression adjusting for gestation, ethnicity, and deprivation. Retained as a reference point; estimates are in <a href="#technical-details">Technical Details</a>.</p></li>
<li><p>Model 2 (Mixed effects, gestation only): Hierarchical logistic regression with random intercepts for delivery trust, adjusting only for gestation among clinical covariates <span class="math display">\[\text{logit}(P[\text{NCC}]) = \beta_0 + \beta_1 \text{Gestation} + \beta_2 \text{Ethnicity} + \beta_3 \text{IMD} + u_j\]</span> where <span class="math inline">\(u_j \sim N(0, \sigma^2_u)\)</span> represents the random effect for delivery trust <span class="math inline">\(j\)</span>. Reported because it uses the maximum sample size (gestation is near-completely observed).</p></li>
<li><p>Model 3 (Mixed effects, full clinical adjustment): Adds birth weight and Apgar 5-minute score to Model 2’s specification <span class="math display">\[\text{logit}(P[\text{NCC}]) = \beta_0 + \beta_1 \text{Gestation} + \beta_2 \text{BirthWeight} + \beta_3 \text{Apgar} + \beta_4 \text{Ethnicity} + \beta_5 \text{IMD} + u_j\]</span></p></li>
</ol>
<p>Conceptually Model 3 is the preferred specification — it adjusts for the clinical case-mix that drives NCC need rather than relying on gestation alone — and we lead the interpretation with its results. Model 2 is reported in parallel because of its larger sample (gestation is observed for nearly all births, whereas birth weight and Apgar are observed for 45.9% of the primary sample). Where the two models disagree (notably for Pakistani and Indian ethnic groups), the disagreement itself is informative and is discussed below.</p>
</section>
<section id="birth-weight-data-source" class="level2" data-number="1.6">
<h2 data-number="1.6" class="anchored" data-anchor-id="birth-weight-data-source"><span class="header-section-number">1.6</span> Birth Weight Data Source</h2>
<p>The sensitivity model uses birth weight from MSDS only (<code>Birth_Weight_Grams</code>), not the combined MSDS+CC variable. This avoids differential missingness bias: the CC data has 94% birth weight completeness for NCC babies vs 46% for non-NCC babies, which would artificially inflate NCC rates in complete cases.</p>
</section>
<section id="random-effect-grouping" class="level2" data-number="1.7">
<h2 data-number="1.7" class="anchored" data-anchor-id="random-effect-grouping"><span class="header-section-number">1.7</span> Random-effect Grouping</h2>
<p>The hierarchical models cluster babies at the level of the submitting NHS trust (3-letter provider code), not the individual delivery site (5-letter code). Two practical considerations drove this:</p>
<ol type="1">
<li><p><em>Coverage.</em> MSDS populates the site-of-delivery field (<code>Org_Site_ID_Actual_Place_Delivery</code>) for ~83% of babies; the remaining ~17% have no site recorded but do have a submitting-trust code (<code>OrgCodeProvider</code>) populated for 100% of records. The no-site cohort is concentrated in 15 large multi-site trusts and is not random with respect to outcome (NCC rate 14.2% vs 11.5% in the with-site cohort), ethnicity (more Pakistani, fewer Indian) or deprivation. Excluding it on a missing-site filter would bias the model.</p></li>
<li><p><em>Hierarchy.</em> Site codes (e.g.&nbsp;<code>RYJ01</code>) sit administratively <em>inside</em> trust codes (e.g.&nbsp;<code>RYJ</code>). Treating “RYJ01” babies and “RYJ-trust-only” babies as independent random-effect groups would double-count trust-level variance and break the exchangeability assumption. Clustering at trust level for everyone keeps a single consistent rung.</p></li>
</ol>
<p>The grouping variable is constructed as <code>Delivery_Trust = coalesce(LEFT(Delivery_Site_Code, 3), Submitting_Org_Code)</code>, then used as the random-intercept term <code>(1 | Delivery_Trust)</code>. For multi-site trusts (Imperial, Leicester, Barts, etc.), within-trust between-site variation is folded into the residual rather than the random effect; the reported ICC is therefore a slightly conservative estimate of between-hospital variation.</p>
<section id="why-mixed-effects" class="level3" data-number="1.7.1">
<h3 data-number="1.7.1" class="anchored" data-anchor-id="why-mixed-effects"><span class="header-section-number">1.7.1</span> Why mixed effects?</h3>
<p>A standard regression would treat all 500,000+ babies as independent draws from one giant, uniform hospital. They are not: babies are clustered within trusts, and the baseline likelihood of NCC admission varies widely between trusts — through clinical thresholds, local capacity and reporting practice. Ignoring that clustering has two costs. It understates uncertainty (babies within a hospital partly repeat the same hospital-level information), and it can generate false findings: if an ethnic group happens to be concentrated around hospitals that admit (or report) more, a standard model would attribute the hospital’s behaviour to the group.</p>
<p>The mixed-effects model fixes this by giving each trust its own baseline admission rate (a “random intercept”), with the trust baselines treated as draws from a common distribution. The patient-level effects — ethnicity, deprivation, clinical need — are then estimated with the hospital baseline held constant. So when we report that the most deprived quintile has 9.4% higher odds of admission, it means: for two clinically identical babies born in the <em>same</em> trust, the baby from the most deprived area is 9.4% more likely to be admitted.</p>
<hr>
</section>
</section>
</section>
<section id="results" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Results</h1>
<section id="model-2-mixed-effects-logistic-regression" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="model-2-mixed-effects-logistic-regression"><span class="header-section-number">2.1</span> Model 2: Mixed Effects Logistic Regression</h2>
<p>The primary model. Random intercepts for delivery trust allow each provider its own baseline NCC admission rate; a fixed-effects-only reference fit (Model 1) is in <a href="#technical-details">Technical Details</a>.</p>
<section id="fixed-effects-odds-ratios" class="level3" data-number="2.1.1">
<h3 data-number="2.1.1" class="anchored" data-anchor-id="fixed-effects-odds-ratios"><span class="header-section-number">2.1.1</span> Fixed Effects (Odds Ratios)</h3>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed caption-top table-sm small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Variable</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Odds Ratio</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">95% CI</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p-value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p (BH-adj)</th>
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd" data-grouplength="1">
<td colspan="6" style="border-bottom: 1px solid"><strong>Clinical</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Gestation (per week)</td>
<td style="text-align: right;">0.619</td>
<td style="text-align: center;">(0.616, 0.622)</td>
<td style="text-align: right;">&lt;0.001</td>
<td style="text-align: right;">—</td>
<td style="text-align: left;">***</td>
</tr>
<tr class="odd" data-grouplength="9">
<td colspan="6" style="border-bottom: 1px solid"><strong>Ethnicity (ref: White British)</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Ethnicity: White Other</td>
<td style="text-align: right;">0.924</td>
<td style="text-align: center;">(0.892, 0.958)</td>
<td style="text-align: right;">&lt;0.001</td>
<td style="text-align: right;">&lt;0.001</td>
<td style="text-align: left;">***</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Ethnicity: Mixed</td>
<td style="text-align: right;">0.942</td>
<td style="text-align: center;">(0.905, 0.981)</td>
<td style="text-align: right;">0.004</td>
<td style="text-align: right;">0.008</td>
<td style="text-align: left;">**</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Ethnicity: Indian</td>
<td style="text-align: right;">1.054</td>
<td style="text-align: center;">(1.005, 1.105)</td>
<td style="text-align: right;">0.032</td>
<td style="text-align: right;">0.048</td>
<td style="text-align: left;">*</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Ethnicity: Pakistani</td>
<td style="text-align: right;">0.889</td>
<td style="text-align: center;">(0.845, 0.935)</td>
<td style="text-align: right;">&lt;0.001</td>
<td style="text-align: right;">&lt;0.001</td>
<td style="text-align: left;">***</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Ethnicity: Bangladeshi</td>
<td style="text-align: right;">1.060</td>
<td style="text-align: center;">(0.976, 1.15)</td>
<td style="text-align: right;">0.169</td>
<td style="text-align: right;">0.19</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Ethnicity: Other Asian</td>
<td style="text-align: right;">1.013</td>
<td style="text-align: center;">(0.954, 1.074)</td>
<td style="text-align: right;">0.679</td>
<td style="text-align: right;">0.679</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Ethnicity: Black</td>
<td style="text-align: right;">1.037</td>
<td style="text-align: center;">(0.994, 1.082)</td>
<td style="text-align: right;">0.089</td>
<td style="text-align: right;">0.115</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Ethnicity: Chinese</td>
<td style="text-align: right;">0.695</td>
<td style="text-align: center;">(0.578, 0.835)</td>
<td style="text-align: right;">&lt;0.001</td>
<td style="text-align: right;">&lt;0.001</td>
<td style="text-align: left;">***</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Ethnicity: Other</td>
<td style="text-align: right;">0.926</td>
<td style="text-align: center;">(0.865, 0.991)</td>
<td style="text-align: right;">0.027</td>
<td style="text-align: right;">0.048</td>
<td style="text-align: left;">*</td>
</tr>
<tr class="odd" data-grouplength="4">
<td colspan="6" style="border-bottom: 1px solid"><strong>Deprivation (ref: Least Deprived)</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">IMD: 4</td>
<td style="text-align: right;">1.016</td>
<td style="text-align: center;">(0.981, 1.051)</td>
<td style="text-align: right;">0.383</td>
<td style="text-align: right;">0.383</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">IMD: 3</td>
<td style="text-align: right;">1.063</td>
<td style="text-align: center;">(1.027, 1.1)</td>
<td style="text-align: right;">&lt;0.001</td>
<td style="text-align: right;">&lt;0.001</td>
<td style="text-align: left;">***</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">IMD: 2</td>
<td style="text-align: right;">1.108</td>
<td style="text-align: center;">(1.071, 1.147)</td>
<td style="text-align: right;">&lt;0.001</td>
<td style="text-align: right;">&lt;0.001</td>
<td style="text-align: left;">***</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">IMD: 1 - Most deprived</td>
<td style="text-align: right;">1.101</td>
<td style="text-align: center;">(1.064, 1.14)</td>
<td style="text-align: right;">&lt;0.001</td>
<td style="text-align: right;">&lt;0.001</td>
<td style="text-align: left;">***</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="padding: 0; border: 0"><sup></sup> BH-adjusted p-values are computed within each test family separately (9 ethnicity contrasts; 4 IMD contrasts).</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
</tfoot>

</table>
</div>
</div>
</section>
<section id="forest-plot-ethnicity-and-deprivation" class="level3" data-number="2.1.2">
<h3 data-number="2.1.2" class="anchored" data-anchor-id="forest-plot-ethnicity-and-deprivation"><span class="header-section-number">2.1.2</span> Forest Plot: Ethnicity and Deprivation</h3>
<div class="cell">
<div class="cell-output-display">
<div id="fig-forest" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-forest-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="technical_appendix_files/figure-html/fig-forest-1.png" class="img-fluid figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-forest-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Odds ratios for NCC admission by ethnicity and deprivation (adjusted for gestation, with hospital random effects)
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="random-effects-hospital-variation" class="level3" data-number="2.1.3">
<h3 data-number="2.1.3" class="anchored" data-anchor-id="random-effects-hospital-variation"><span class="header-section-number">2.1.3</span> Random Effects: Hospital Variation</h3>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed caption-top table-sm small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Metric</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Random effect variance (delivery trust)</td>
<td style="text-align: right;">1.5236</td>
</tr>
<tr class="even">
<td style="text-align: left;">Random effect SD</td>
<td style="text-align: right;">1.2343</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Intraclass Correlation (ICC)</td>
<td style="text-align: right;">0.3165</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of delivery trusts</td>
<td style="text-align: right;">131.0000</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The intraclass correlation coefficient (ICC) of 0.317 means that approximately 31.7% of the unexplained variation in NCC admission, after accounting for gestation, ethnicity and deprivation, sits between delivery trusts rather than between babies. This is the largest residual signal in the model, but it bundles clinical practice, capacity, case-mix and reporting differences together; what it can and cannot be taken to mean is discussed under <a href="#hospital-variation">Hospital Variation</a>. Because clustering is at trust rather than site level, variation between sites in the same trust is absorbed into the residual rather than the random effect. The ICC is therefore a slightly conservative estimate of between-hospital variation.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-caterpillar" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-caterpillar-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="technical_appendix_files/figure-html/fig-caterpillar-1.png" class="img-fluid figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-caterpillar-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Hospital-level effects ranked from lowest to highest NCC admission rate (after case-mix adjustment)
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="funnel-plot-case-mix-adjusted-admission-rates" class="level3" data-number="2.1.4">
<h3 data-number="2.1.4" class="anchored" data-anchor-id="funnel-plot-case-mix-adjusted-admission-rates"><span class="header-section-number">2.1.4</span> Funnel Plot: Case-mix-adjusted Admission Rates</h3>
<p>The review suggested a funnel plot — as used in the GIRFT programme — as an alternative to the caterpillar plot above. The two show the same trust-level variation but answer slightly different questions. The caterpillar ranks trusts by their estimated random effect; the funnel asks, more directly, <em>which trusts admit at a rate that case-mix alone cannot explain?</em></p>
<p>Each trust is plotted against the number of NCC admissions expected given the case-mix of the babies born there (gestation, ethnicity and deprivation), using the fixed-effects part of the primary model, i.e.&nbsp;with the trust’s own random effect removed. The horizontal line is the national crude NCC rate across the trusts plotted (~12%; this is computed on the complete-case modelling sample used for the funnel and so sits marginally below the ~13% rate for the full birth cohort reported elsewhere). The curved lines are 95% and 99.8% control limits. A trust inside the funnel is varying no more than chance would predict; a trust outside the 99.8% (≈3-sigma) limit is a statistical outlier. Because the genuine between-trust variation is large (the same signal as the ICC), the limits are widened to account for this overdispersion (see the method note below), so that only the most extreme trusts are flagged rather than the majority.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-funnel" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-funnel-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="technical_appendix_files/figure-html/fig-funnel-1.png" class="img-fluid figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-funnel-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Funnel plot of case-mix-adjusted NCC admission rates by delivery trust. Points outside the 99.8% limits admit at a rate that case-mix and chance alone do not explain. Adjusted for gestation, ethnicity and IMD via the primary model’s fixed effects (trust random effect removed).
</figcaption>
</figure>
</div>
</div>
</div>
<p>An extreme position can reflect genuine practice variation, but equally a tertiary referral centre (which legitimately admits more), or a provider whose MSDS / PbR-CC submission is out of step with peers. The table below flags each 99.8% outlier with its neonatal unit type (NICU units are tertiary and expected to sit high) and its MSDS source share — the proportion of the trust’s NCC babies that appear in the MSDS neonatal record rather than only in the CC extract. A low share points to under-submission in MSDS and heavier reliance on the CC source: a data-quality signal rather than a clinical one. Note, though, that a low share changes <em>where</em> an admission is recorded, not <em>whether</em> it is counted — the combined admission flag picks a baby up from either source — so MSDS under-submission cannot by itself inflate a trust’s admission rate (see the diagnostic below).</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed caption-top table-sm small">
<caption>Trusts outside the 99.8% control limits (4 higher than expected, 0 lower)</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Outlier</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Unit type</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Births</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Observed rate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Adjusted rate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">SAR</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Direction</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">MSDS source share</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Outlier 1</td>
<td style="text-align: left;">LNU</td>
<td style="text-align: right;">4,967</td>
<td style="text-align: right;">44.2%</td>
<td style="text-align: right;">46.5%</td>
<td style="text-align: right;">3.89</td>
<td style="text-align: left;">Higher than expected</td>
<td style="text-align: right;">15%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Outlier 2</td>
<td style="text-align: left;">NICU</td>
<td style="text-align: right;">4,720</td>
<td style="text-align: right;">28.5%</td>
<td style="text-align: right;">27.6%</td>
<td style="text-align: right;">2.30</td>
<td style="text-align: left;">Higher than expected</td>
<td style="text-align: right;">1%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Outlier 3</td>
<td style="text-align: left;">NICU</td>
<td style="text-align: right;">6,889</td>
<td style="text-align: right;">29%</td>
<td style="text-align: right;">27.3%</td>
<td style="text-align: right;">2.28</td>
<td style="text-align: left;">Higher than expected</td>
<td style="text-align: right;">0%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Outlier 4</td>
<td style="text-align: left;">LNU</td>
<td style="text-align: right;">10,324</td>
<td style="text-align: right;">25.8%</td>
<td style="text-align: right;">26.7%</td>
<td style="text-align: right;">2.23</td>
<td style="text-align: left;">Higher than expected</td>
<td style="text-align: right;">32%</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>At face value the four flagged trusts appear to split into two groups: two tertiary NICUs whose MSDS source share is near zero, suggesting a reporting gap combined with referral-centre activity, and two local neonatal units (LNUs) admitting well above expectation. An earlier draft of this section presented that reading. Follow-up discussion raised a fair challenge: is the outlier signal about the completeness of the records these trusts submit, or the completeness of specific fields on records that are present? The diagnostic below tests both mechanisms directly and finds that neither holds; all four outliers share a different signature.</p>
<section id="outlier-completeness" class="level4" data-number="2.1.4.1">
<h4 data-number="2.1.4.1" class="anchored" data-anchor-id="outlier-completeness"><span class="header-section-number">2.1.4.1</span> Missing records, missing fields, or a broader numerator?</h4>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>The three mechanisms tested, and why two are ruled out (click to expand)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Three data mechanisms could place a trust spuriously outside the funnel:</p>
<ol type="1">
<li>Record-level completeness: the trust submits few MSDS birth records, so its denominator is a small, unrepresentative slice of its true delivery population.</li>
<li>Field-level completeness: births are submitted, but the model fields (gestation, ethnicity, IMD) are missing, so the complete-case sample keeps a selected, likely sicker and better-documented, subset of its births.</li>
<li>Numerator breadth: the denominator is sound, but the trust’s PbR-CC return counts more of its neonatal unit activity as “NCC” days than peers’ returns do.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed caption-top table-sm small">
<caption>Completeness and numerator diagnostics for the funnel outliers, against all other trusts. Outlier numbering matches the outlier table above.</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Trust</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Births</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">All model fields present</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Preterm (&lt;37w) births</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">NCC rate, all births</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">NCC rate, term births</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">NCC in CC source only</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">NCC stays of 2 days or less</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Outlier 1</td>
<td style="text-align: right;">5,343</td>
<td style="text-align: right;">93%</td>
<td style="text-align: right;">8.3%</td>
<td style="text-align: right;">41.5%</td>
<td style="text-align: right;">39.9%</td>
<td style="text-align: right;">85%</td>
<td style="text-align: right;">72%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Outlier 2</td>
<td style="text-align: right;">4,868</td>
<td style="text-align: right;">97%</td>
<td style="text-align: right;">8.5%</td>
<td style="text-align: right;">29.0%</td>
<td style="text-align: right;">23.0%</td>
<td style="text-align: right;">99%</td>
<td style="text-align: right;">40%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Outlier 3</td>
<td style="text-align: right;">6,932</td>
<td style="text-align: right;">99%</td>
<td style="text-align: right;">8.7%</td>
<td style="text-align: right;">29.0%</td>
<td style="text-align: right;">24.3%</td>
<td style="text-align: right;">100%</td>
<td style="text-align: right;">39%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Outlier 4</td>
<td style="text-align: right;">10,822</td>
<td style="text-align: right;">95%</td>
<td style="text-align: right;">7.7%</td>
<td style="text-align: right;">25.5%</td>
<td style="text-align: right;">21.0%</td>
<td style="text-align: right;">68%</td>
<td style="text-align: right;">47%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">All other trusts</td>
<td style="text-align: right;">478,691</td>
<td style="text-align: right;">94%</td>
<td style="text-align: right;">7.9%</td>
<td style="text-align: right;">10.9%</td>
<td style="text-align: right;">7.2%</td>
<td style="text-align: right;">74%</td>
<td style="text-align: right;">24%</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The table rules out the first two mechanisms for all four outliers:</p>
<ul>
<li>Their birth records are present in expected volumes: each outlier trust submitted between roughly 4,900 and 10,800 births — all above the median trust (~3,700) — in line with their real delivery-service size. This is nothing like a missing-denominator pattern.</li>
<li>Their field completeness is unremarkable: 93–99% of their births carry all three model fields (nationally 94%), and each trust’s crude NCC rate is essentially unchanged when restricted to the model-usable subset. Complete-case selection is not what lifts them out of the funnel.</li>
<li>A third explanation also fails on arithmetic: referral activity cannot raise a trust’s position in a delivery-cohort funnel. The funnel counts babies <em>born</em> at each trust, and over 99% of the NCC recorded for those babies was provided by the delivery trust itself. Transfers into a tertiary unit never enter its numerator here.</li>
</ul>
</div>
</div>
</div>
<p>What remains — and what the diagnostic table above shows — is the third data mechanism. At the outlier trusts, 21–40% of <em>term</em> (≥37-week) babies carry an NCC record, against ~7% everywhere else, while their preterm birth shares are unremarkable (7.7–8.7%, national 7.9%). Their admitted babies are correspondingly term-heavy and their recorded stays short; at three of the four trusts the admissions are also recorded almost entirely in the CC extract. A true critical-care rate of one in four term births is not clinically plausible; the far more likely reading is that these providers return a broader span of neonatal unit activity — special or transitional care, possibly routine observation — as NCC critical-care days in PbR-CC. This extract cannot fully separate “admits more term babies to the unit” (practice) from “codes more unit days as critical care” (recording), because the care-level fields that would settle it (Level 2/3 days, unit function) are unpopulated here; but the recording component is likely dominant.</p>
<p>Two consequences follow. First, the NICU-vs-LNU split above no longer holds: the near-zero MSDS source share at the two NICU outliers is a genuine reporting gap, but it cannot inflate their rate, and all four outliers share the same term-heavy, short-stay signature. Second, the practical follow-up changes: the first question for these trusts concerns what unit activity their PbR-CC return counts as an NCC day — a data-definition conversation before a clinical-practice one. This also sharpens the caution attached to the ICC throughout this report: a material share of the apparent between-trust variation is reporting breadth, not admission practice. (Trust identities are held internally and omitted from this published version.)</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>How the funnel is built (click to expand)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Expected admissions are the population-average (case-mix only) predictions from the primary model with the trust random effect removed (<code>predict(..., re.form = NA)</code>), aggregated per trust and indirectly standardised so the national observed/expected ratio is 1. Control limits use the standard funnel formulation (Spiegelhalter, <em>Statistics in Medicine</em>, 2005): on the standardised-ratio scale the limits are <span class="math inline">\(1 \pm z\sqrt{\phi}/\sqrt{E}\)</span>, shown here multiplied by the national crude rate.</p>
<p>Because between-trust variation here is far larger than binomial sampling noise (the same signal as the ICC), the limits include a multiplicative overdispersion factor <span class="math inline">\(\phi\)</span>, estimated from the winsorised standardised residuals so that a handful of extreme trusts do not themselves inflate it. Without this adjustment almost every trust would fall outside the limits — a true reflection of the large ICC, but useless for isolating individual outliers. Even so, the same data-quality caveats apply as to the ICC: MSDS / PbR-CC submission completeness varies between providers, so outliers should be read as flags for follow-up, not as confirmed differences in admission practice. The completeness diagnostic above shows how to separate these readings — for the current outliers the evidence points to numerator breadth in the PbR-CC return rather than either missing records or missing fields.</p>
</div>
</div>
</div>
<hr>
</section>
</section>
</section>
</section>
<section id="interpretation" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Interpretation</h1>
<section id="clinical-factors" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="clinical-factors"><span class="header-section-number">3.1</span> Clinical Factors</h2>
<p>Gestation is by far the strongest predictor of NCC admission: each additional week reduces the odds by approximately 38%. Preterm babies are correspondingly more likely to be admitted, confirming that the model is capturing genuine clinical need.</p>
</section>
<section id="ethnicity" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="ethnicity"><span class="header-section-number">3.2</span> Ethnicity</h2>
<p>After adjusting for gestation and comparing within trusts, most ethnic groups sit within a few percent of parity with White British babies (full estimates in the Model 2 table and <a href="#fig-forest" class="quarto-xref">Figure&nbsp;1</a>). The Black group sits at near-exact parity; Pakistani and Chinese babies sit below parity in this model; Indian and Bangladeshi babies sit slightly above. How each estimate responds when birth weight and Apgar are added is the key to interpreting them:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 22%">
<col style="width: 32%">
<col style="width: 32%">
</colgroup>
<thead>
<tr class="header">
<th>Group</th>
<th>Primary OR</th>
<th>Sensitivity OR</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Pakistani</td>
<td>0.89</td>
<td>0.97</td>
<td>Moves towards parity — clinical factors explain much of the difference</td>
</tr>
<tr class="even">
<td>Chinese</td>
<td>0.70</td>
<td>0.76</td>
<td>Still notably lower, at the boundary of nominal significance in the smaller sample</td>
</tr>
<tr class="odd">
<td>Indian</td>
<td>1.05</td>
<td>1.16</td>
<td>Increases further — higher access after clinical adjustment</td>
</tr>
<tr class="even">
<td>Bangladeshi</td>
<td>1.06</td>
<td>1.17</td>
<td>Similar pattern to Indian</td>
</tr>
<tr class="odd">
<td>Black</td>
<td>1.04</td>
<td>1.04</td>
<td>Stable — consistent with equitable access</td>
</tr>
</tbody>
</table>
<p>The Pakistani estimate is largely a case-mix finding: the lower odds in the primary model move to near-parity once birth weight and Apgar are adjusted for. The Indian and Bangladeshi estimates move further above parity, suggesting NCC use at least proportionate to clinical need. The differences among Indian, Pakistani and Bangladeshi babies after adjustment are the clearest demonstration of why this report uses disaggregated ethnicity coding.</p>
<p>The Chinese group is the largest unexplained deviation: around 24% lower odds remain after clinical adjustment (the BH-adjusted p-value in the Model 2 table is the appropriate test of evidence). Three broad explanations are consistent with this, and the data cannot separate them:</p>
<ul>
<li>Unmeasured clinical need — Chinese babies have lower mean birth weight at term in UK data, and the cohort likely differs from the reference group in maternal age structure, parity, and rates of high-risk pregnancy; gestation alone, and a single linear birth-weight term in the sensitivity model, may not fully capture this.</li>
<li>Sample size — Chinese is one of the smaller ethnic groups in the cohort, so the estimate is less stable than the odds ratio alone suggests.</li>
<li>Data and access factors — two distinct possibilities the data cannot tell apart: genuine differences in care-seeking or antenatal engagement (including selective use of private antenatal care), and possible under-recording of NCC episodes in this group. Neither has direct evidence for or against it here.</li>
</ul>
<p>Distinguishing these would need richer clinical covariates or direct engagement with providers (see <a href="modelling_results.html#recommendations">Recommendations</a> in the Findings report). The estimate should be treated as a question rather than a conclusion.</p>
<section id="broad-ethnicity" class="level3" data-number="3.2.1">
<h3 data-number="3.2.1" class="anchored" data-anchor-id="broad-ethnicity"><span class="header-section-number">3.2.1</span> A broad, MBRRACE-comparable grouping</h3>
<p>MBRRACE-UK reports present their headline ethnicity findings using broad groups (White, Mixed, Asian, Black, Other), and it is a fair question whether the ten-category grouping used here is more detailed than the data can support. To allow direct comparison, the primary model was refitted on the same 476,475 births with ethnicity collapsed to the five broad ONS groups; every other part of the model specification is unchanged. The broad grouping is an exact aggregation of the detailed one (each detailed category maps into exactly one broad group), so any difference between the two tables below is purely a consequence of the grouping choice.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed caption-top table-sm small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Broad group</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Births</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Odds Ratio</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">95% CI</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p (BH-adj)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Mixed</td>
<td style="text-align: right;">34,021</td>
<td style="text-align: right;">0.955</td>
<td style="text-align: center;">(0.918, 0.994)</td>
<td style="text-align: right;">0.033</td>
</tr>
<tr class="even">
<td style="text-align: left;">Asian or Asian British</td>
<td style="text-align: right;">72,199</td>
<td style="text-align: right;">1.003</td>
<td style="text-align: center;">(0.973, 1.035)</td>
<td style="text-align: right;">0.834</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Black or Black British</td>
<td style="text-align: right;">31,079</td>
<td style="text-align: right;">1.054</td>
<td style="text-align: center;">(1.011, 1.099)</td>
<td style="text-align: right;">0.026</td>
</tr>
<tr class="even">
<td style="text-align: left;">Other (incl. Chinese)</td>
<td style="text-align: right;">14,110</td>
<td style="text-align: right;">0.907</td>
<td style="text-align: center;">(0.851, 0.967)</td>
<td style="text-align: right;">0.011</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="text-align: left; padding: 0; border: 0;"><sup></sup> Reference: White (n = 325,066). Same model specification and sample as Model 2; only the ethnicity grouping differs. BH adjustment across the 4 broad contrasts.</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: center;"></td>
<td style="text-align: right;"></td>
</tr>
</tfoot>

</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-broad-ethnicity" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-broad-ethnicity-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="technical_appendix_files/figure-html/fig-broad-ethnicity-1.png" class="img-fluid figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-broad-ethnicity-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Broad MBRRACE-style ethnicity groups (diamonds) and the detailed groups they contain (circles), from two otherwise-identical models on the same births. The broad ‘Asian or Asian British’ estimate averages away the opposite-signed Indian/Bangladeshi and Pakistani patterns; the Chinese estimate is absorbed into ‘Other’.
</figcaption>
</figure>
</div>
</div>
</div>
<p>At the broad level the picture is straightforward: the Asian or Asian British group sits at OR 1.00, the Black or Black British group at 1.05, and no broad group deviates dramatically from the White reference. This is a useful headline for comparison with MBRRACE-style reporting, and it confirms that no broad ethnic group faces large systematic under-admission at national level.</p>
<p><a href="#fig-broad-ethnicity" class="quarto-xref">Figure&nbsp;4</a> shows what the aggregation costs. The single broad Asian estimate is a weighted average of detailed groups whose estimates point in opposite directions — Pakistani below parity, Indian and Bangladeshi above it (a spread from 0.89 to 1.06) — and these are not noise: the sensitivity analysis showed they respond differently to clinical adjustment, as would be expected of real, distinct patterns of need and access. Likewise, the Chinese group — the largest single-group deviation in the analysis (OR 0.70) — is diluted into the broad “Other” category, where a 30% deficit attached to an identifiable group becomes a 9% deficit attached to a heterogeneous residual one. A model using only broad groups would have reported near-exact parity for Asian babies and a modest unattributable deficit for “Other”, losing the two most interpretable ethnicity findings in this report.</p>
<p>This is why the report leads with the detailed grouping and treats the broad grouping as a comparability view rather than the primary analysis. The multiple-testing cost of the extra detail is handled explicitly (Benjamini–Hochberg adjustment within the ethnicity family), and MBRRACE itself disaggregates beyond the broad groups in its extended tables where numbers allow. The recommendation that follows concerns reporting, not remodelling: broad groups are the right currency for headline cross-programme comparison, but equity monitoring should retain the disaggregated view, because the groups with the clearest signals in these data are precisely the ones the broad categories average away.</p>
</section>
</section>
<section id="focus-black-ethnicity-and-the-maternity-review-context" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="focus-black-ethnicity-and-the-maternity-review-context"><span class="header-section-number">3.3</span> Focus: Black Ethnicity and the Maternity Review Context</h2>
<p>Given the focus of recent maternity reviews on outcomes for Black mothers and babies, this section provides detailed analysis of NCC access for Black ethnic groups.</p>
<section id="raw-ncc-admission-rates" class="level3" data-number="3.3.1">
<h3 data-number="3.3.1" class="anchored" data-anchor-id="raw-ncc-admission-rates"><span class="header-section-number">3.3.1</span> Raw NCC Admission Rates</h3>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed caption-top table-sm small">
<caption>NCC admission rates by Black ethnic subgroup</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Ethnic Group</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Births</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">NCC Admissions</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">NCC Rate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">White British</td>
<td style="text-align: right;">275,252</td>
<td style="text-align: right;">34,837</td>
<td style="text-align: right;">12.7%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Black Caribbean</td>
<td style="text-align: right;">3,985</td>
<td style="text-align: right;">501</td>
<td style="text-align: right;">12.6%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Black African</td>
<td style="text-align: right;">24,530</td>
<td style="text-align: right;">3,142</td>
<td style="text-align: right;">12.8%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Other Black</td>
<td style="text-align: right;">3,443</td>
<td style="text-align: right;">453</td>
<td style="text-align: right;">13.2%</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Black babies have NCC admission rates essentially identical to White British babies (13.4–13.8% vs 13.4%), and the model estimates confirm this: OR 1.04 in the primary model, unchanged at 1.04 after clinical adjustment in the sensitivity model. This contrasts with the Pakistani and Chinese groups, which show lower admission rates.</p>
</section>
<section id="clinical-context-higher-need-equitable-access" class="level3" data-number="3.3.2">
<h3 data-number="3.3.2" class="anchored" data-anchor-id="clinical-context-higher-need-equitable-access"><span class="header-section-number">3.3.2</span> Clinical Context: Higher Need, Equitable Access</h3>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed caption-top table-sm small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Characteristic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">White British</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Black</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Mean birth weight (g)</td>
<td style="text-align: right;">3,322</td>
<td style="text-align: right;">3,196</td>
</tr>
<tr class="even">
<td style="text-align: left;">Low birth weight (&lt;2500g)</td>
<td style="text-align: right;">7.8%</td>
<td style="text-align: right;">9.9%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Low Apgar 5-min (&lt;7)</td>
<td style="text-align: right;">2.1%</td>
<td style="text-align: right;">3.0%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Most deprived IMD quintile</td>
<td style="text-align: right;">19.8%</td>
<td style="text-align: right;">44.6%</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Black babies carry higher clinical need on average — lower mean birth weight, higher rates of low Apgar scores, and a much higher concentration in the most deprived areas. Despite these risk factors, admission rates are similar, and after clinical adjustment Black babies show slightly higher odds of admission (OR 1.04), consistent with the system responding to clinical need.</p>
</section>
<section id="hospital-level-variation" class="level3" data-number="3.3.3">
<h3 data-number="3.3.3" class="anchored" data-anchor-id="hospital-level-variation"><span class="header-section-number">3.3.3</span> Hospital-Level Variation</h3>
<p>While overall access is equitable, there is variation between providers:</p>
<ul>
<li>93 trusts have sufficient Black births (≥50) for comparison</li>
<li>61 (66%) have Black NCC rates higher than White</li>
<li>13 trusts have disparities exceeding 5 percentage points</li>
<li>Mean difference: +1.3 percentage points (Black vs White)</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed caption-top table-sm small">
<caption>Trusts with &gt;5pp Black-White NCC rate disparity</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Trust</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Black Rate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">White Rate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Difference</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Black Births</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Direction</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Trust 1</td>
<td style="text-align: right;">36.3%</td>
<td style="text-align: right;">24%</td>
<td style="text-align: right;">+12.2pp</td>
<td style="text-align: right;">601</td>
<td style="text-align: left;">Black higher</td>
</tr>
<tr class="even">
<td style="text-align: left;">Trust 2</td>
<td style="text-align: right;">31.4%</td>
<td style="text-align: right;">19.6%</td>
<td style="text-align: right;">+11.9pp</td>
<td style="text-align: right;">194</td>
<td style="text-align: left;">Black higher</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Trust 3</td>
<td style="text-align: right;">37.9%</td>
<td style="text-align: right;">28.1%</td>
<td style="text-align: right;">+9.8pp</td>
<td style="text-align: right;">253</td>
<td style="text-align: left;">Black higher</td>
</tr>
<tr class="even">
<td style="text-align: left;">Trust 4</td>
<td style="text-align: right;">36%</td>
<td style="text-align: right;">27.2%</td>
<td style="text-align: right;">+8.8pp</td>
<td style="text-align: right;">50</td>
<td style="text-align: left;">Black higher</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Trust 5</td>
<td style="text-align: right;">22.4%</td>
<td style="text-align: right;">13.7%</td>
<td style="text-align: right;">+8.7pp</td>
<td style="text-align: right;">98</td>
<td style="text-align: left;">Black higher</td>
</tr>
<tr class="even">
<td style="text-align: left;">Trust 6</td>
<td style="text-align: right;">19.2%</td>
<td style="text-align: right;">12.3%</td>
<td style="text-align: right;">+6.9pp</td>
<td style="text-align: right;">167</td>
<td style="text-align: left;">Black higher</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Trust 7</td>
<td style="text-align: right;">15.4%</td>
<td style="text-align: right;">9.5%</td>
<td style="text-align: right;">+5.9pp</td>
<td style="text-align: right;">52</td>
<td style="text-align: left;">Black higher</td>
</tr>
<tr class="even">
<td style="text-align: left;">Trust 8</td>
<td style="text-align: right;">22.5%</td>
<td style="text-align: right;">16.7%</td>
<td style="text-align: right;">+5.8pp</td>
<td style="text-align: right;">178</td>
<td style="text-align: left;">Black higher</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Trust 9</td>
<td style="text-align: right;">16.9%</td>
<td style="text-align: right;">11.4%</td>
<td style="text-align: right;">+5.5pp</td>
<td style="text-align: right;">249</td>
<td style="text-align: left;">Black higher</td>
</tr>
<tr class="even">
<td style="text-align: left;">Trust 10</td>
<td style="text-align: right;">21.6%</td>
<td style="text-align: right;">16.3%</td>
<td style="text-align: right;">+5.3pp</td>
<td style="text-align: right;">574</td>
<td style="text-align: left;">Black higher</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="black-underaccess-screen" class="level3" data-number="3.3.4">
<h3 data-number="3.3.4" class="anchored" data-anchor-id="black-underaccess-screen"><span class="header-section-number">3.3.4</span> Trust-level screen for lower Black admission rates</h3>
<p>The review asked specifically whether any individual trusts admit Black babies to NCC at a <em>significantly lower</em> rate than White babies — the signal we would expect if there were localised under-admission. To test this we compared the crude NCC admission rate for Black versus White babies within each trust that had at least 50 of each, using a two-proportion test with Benjamini-Hochberg correction across the trusts tested.</p>
<p>Of the 92 trusts with enough Black and White births to compare, 1 showed a Black admission rate significantly lower than White after correction, and 3 showed a significantly higher rate.</p>
<table class="table table-striped table-hover table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Trusts where Black NCC admission is significantly lower than White (BH-adjusted p &lt; 0.05)
</caption>
<thead>
<tr>
<th style="text-align:left;">
Trust
</th>
<th style="text-align:right;">
Black rate
</th>
<th style="text-align:right;">
White rate
</th>
<th style="text-align:right;">
Difference
</th>
<th style="text-align:right;">
Black births
</th>
<th style="text-align:right;">
p (BH-adj)
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Trust 1 (identity held internally)
</td>
<td style="text-align:right;">
12.9%
</td>
<td style="text-align:right;">
18.8%
</td>
<td style="text-align:right;">
-5.8pp
</td>
<td style="text-align:right;">
666
</td>
<td style="text-align:right;">
0.014
</td>
</tr>
</tbody>
</table>
<p>This is a crude within-trust comparison: it asks whether Black babies are admitted less often than White babies at a given trust, not whether they are admitted less often than their clinical need warrants. Because Black babies in this cohort carry higher average clinical need, a crude rate that is merely equal could still mask relative under-admission. Trust-level power is also limited: many trusts have few Black births, so only sizeable gaps reach significance. Significant trusts are a screen for follow-up rather than confirmation of inequitable access; a case-mix-standardised version (a per-trust Black observed/expected ratio) is the natural refinement.</p>
<p>In the context of recent maternity reviews, the overall picture is that NCC access for Black babies appears equitable on average nationally — a finding about admission only, not about the wider quality of maternity or neonatal care. At provider level, the screen above found one trust (of 92 testable) with a significantly lower Black admission rate, now flagged for a case-mix-standardised follow-up; the remaining variation is within what chance and case-mix would produce. The groups where follow-up should focus are Pakistani and Chinese (see <a href="#ethnicity">Ethnicity</a>).</p>
</section>
</section>
<section id="deprivation" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="deprivation"><span class="header-section-number">3.4</span> Deprivation</h2>
<p>The deprivation gradient suggests babies from more deprived areas have higher odds of NCC admission:</p>
<p>Babies from the most deprived quintile have 2% higher odds of NCC admission than the least deprived, and the gradient steps up consistently across quintiles. Two interpretations are worth separating explicitly, because they carry different implications:</p>
<ul>
<li><em>Deprivation as a proxy for unmeasured need (the most likely reading).</em> Our clinical adjustment — gestation, and in the sensitivity model birth weight and Apgar — almost certainly does not capture the full excess morbidity carried by babies from the most deprived areas. On this reading the gradient is the model responding correctly to higher need that our covariates only partly measure; it is <em>consistent with</em> equitable, need-driven admission rather than evidence of a problem. Supporting this, the gradient is essentially unchanged after birth weight and Apgar are added (see the sensitivity comparison below) — what we would expect if it reflects residual, unmeasured need.</li>
<li><em>A genuine difference in admission propensity.</em> Alternatively, hospitals serving deprived populations may admit at a lower threshold, or high-risk pregnancies may be concentrated in specialist centres in urban/deprived areas. If any part of the gradient reflects a true difference in access rather than need, that would warrant separate investigation.</li>
</ul>
<p>These cannot be fully separated with the current model, but there is a direct check available: if morbidity itself rises across IMD quintiles in this cohort — and especially if it rises in ways the model does not adjust for — the unmeasured-need reading is supported.</p>
<section id="imd-morbidity" class="level3" data-number="3.4.1">
<h3 data-number="3.4.1" class="anchored" data-anchor-id="imd-morbidity"><span class="header-section-number">3.4.1</span> A direct check: morbidity by deprivation quintile</h3>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed caption-top table-sm small">
<caption>Morbidity markers and crude NCC admission by IMD quintile, full 2023/24 birth cohort. Birth-weight measures use the MSDS-only field, recorded for 44–51% of births (completeness is slightly higher in more deprived quintiles).</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">IMD quintile</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Births</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Preterm (&lt;37w)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Very preterm (&lt;32w)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Low birth weight (&lt;2,500g)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">LBW among term births</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Crude NCC rate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1 - Most deprived</td>
<td style="text-align: right;">127,725</td>
<td style="text-align: right;">9.0%</td>
<td style="text-align: right;">1.6%</td>
<td style="text-align: right;">9.3%</td>
<td style="text-align: right;">4.0%</td>
<td style="text-align: right;">12.5%</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: right;">108,771</td>
<td style="text-align: right;">8.1%</td>
<td style="text-align: right;">1.4%</td>
<td style="text-align: right;">8.0%</td>
<td style="text-align: right;">3.2%</td>
<td style="text-align: right;">12.1%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: right;">95,315</td>
<td style="text-align: right;">7.6%</td>
<td style="text-align: right;">1.2%</td>
<td style="text-align: right;">6.9%</td>
<td style="text-align: right;">2.5%</td>
<td style="text-align: right;">11.8%</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: right;">88,804</td>
<td style="text-align: right;">7.3%</td>
<td style="text-align: right;">1.1%</td>
<td style="text-align: right;">6.2%</td>
<td style="text-align: right;">2.2%</td>
<td style="text-align: right;">11.4%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5 - Least deprived</td>
<td style="text-align: right;">80,839</td>
<td style="text-align: right;">6.6%</td>
<td style="text-align: right;">1.0%</td>
<td style="text-align: right;">5.8%</td>
<td style="text-align: right;">2.0%</td>
<td style="text-align: right;">11.3%</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Every morbidity marker rises monotonically with deprivation: relative to the least deprived quintile, preterm birth is about a third higher in the most deprived (9.0% vs 6.6%), very preterm birth about two-thirds higher (1.6% vs 1.0%), and low birth weight around 60% higher (9.4% vs 5.8%). The most telling row is low birth weight among term births, which nearly doubles (4.0% vs 2.1%): the primary model adjusts for gestation, so a deprivation gradient in <em>growth restriction at a given gestation</em> is precisely the kind of clinical need the model cannot see. The crude NCC gradient (12.5% vs 11.3%, a ~11% relative difference) is of the same order as the adjusted odds gradient (~9%), which is what we would expect if the gradient largely reflects need that the clinical adjustment only partly captures.</p>
<p>On this evidence the unmeasured-need reading is well supported: deprivation is acting substantially as a proxy for morbidity our covariates do not fully measure. This does not <em>rule out</em> a residual access difference, but it removes the need to posit one to explain the gradient. The main caveat is birth-weight completeness (44–51%, mildly differential by quintile); the gestation-based markers, which are near-complete, show the same pattern.</p>
</section>
<section id="eth-imd-interaction" class="level3" data-number="3.4.2">
<h3 data-number="3.4.2" class="anchored" data-anchor-id="eth-imd-interaction"><span class="header-section-number">3.4.2</span> Does the deprivation gradient differ by ethnic group?</h3>
<p>The models so far constrain the deprivation gradient to be the <em>same</em> in every ethnic group (and equivalently, ethnicity gaps to be the same in every deprivation quintile). A natural follow-up question is whether the two dimensions of inequality compound — for example, whether deprivation carries a steeper penalty for some ethnic groups than others.</p>
<p>To test this, the primary model was refitted with a full ethnicity × deprivation interaction. The headline result: there is a statistically detectable difference in gradient steepness across groups, but it is small enough that the simpler, single-gradient model remains the right one to use — the detail behind that judgement is below.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>How this was tested (click to expand)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>This is presented as exploratory: the interaction adds 36 parameters, and picking through 36 individual cell contrasts would invite exactly the multiple-comparison problem flagged elsewhere in this report. The primary readout is therefore a single global likelihood-ratio test of whether there is evidence the gradient differs at all, which is one test and carries no multiplicity burden. The within-group estimates below are shown to describe the pattern, not to make claims about any individual group.</p>
<p>The global test does find evidence that the gradient is not uniform: χ²(36) = 65.7, p = 0.0018. But the departure is small. Both information criteria prefer the simpler main-effects model (AIC +6, BIC +405 for the interaction model): with 476,475 births, a likelihood-ratio test is powered to detect departures from uniformity far too small to matter practically. The main-effects model remains the primary specification.</p>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-eth-imd-gradient" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-eth-imd-gradient-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="technical_appendix_files/figure-html/fig-eth-imd-gradient-1.png" class="img-fluid figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-eth-imd-gradient-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Within-group deprivation gradient: odds of NCC admission for the most vs least deprived quintile, estimated separately for each ethnic group (interaction model, adjusted for gestation, with hospital random effects). Dashed line: no gradient. Dotted line: the pooled gradient from the main-effects model. Intervals are wide for smaller groups — exploratory only.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The pattern behind the global signal (<a href="#fig-eth-imd-gradient" class="quarto-xref">Figure&nbsp;5</a>) is informative, read descriptively. The only within-group gradient whose interval excludes 1 is White British (OR 1.13, 95% CI 1.08–1.18) — slightly steeper than the pooled estimate of 1.1. Several minority groups have point estimates of similar or larger magnitude (Indian, Pakistani, Black), but with intervals spanning 1; others (Bangladeshi, Chinese, Other Asian) point flat or below, with very wide intervals. The imprecision is structural rather than incidental: minority ethnic births are concentrated in the more deprived quintiles, so the least-deprived <em>reference</em> cells are small — 306 Bangladeshi and 376 Chinese births in the least deprived quintile, against tens of thousands of White British.</p>
<p>Two conclusions follow. First, there is no evidence that deprivation carries a steeper penalty for minority ethnic groups — the detectable gradient sits within the White British majority, and the pooled deprivation OR reported by the primary model is dominated by that group. Second, that is a statement about the limits of the data as much as about the world: for the smaller groups the data cannot distinguish a flat gradient from a substantial one in either direction, so absence of evidence here is not evidence of absence. Neither conclusion disturbs the <a href="#imd-morbidity">unmeasured-need reading</a> of the main deprivation effect, and the main-effects model remains the primary specification throughout.</p>
</section>
</section>
<section id="hospital-variation" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="hospital-variation"><span class="header-section-number">3.5</span> Hospital Variation</h2>
<p>Once gestation, ethnicity and deprivation are controlled for, the trust a baby is born in is the largest remaining source of variation in the model: the ICC of 0.317 dwarfs the ethnicity ORs (typically 0.87–1.05) and the deprivation OR (1.08 for most vs least deprived). This should not be read simply as “where a baby is born matters most”: the ICC bundles together at least four things this dataset cannot fully separate:</p>
<ol type="1">
<li>Genuine practice variation — different clinical thresholds for NCC admission between hospitals.</li>
<li>Reporting variation — MSDS submission completeness varies considerably between providers, and PbR-CC submission is also patchy. The dual-source <code>NCC_Admitted</code> flag mitigates this but does not eliminate it: nationally the CC source captures ~3.8x more NCC admissions than MSDS alone, and that ratio differs by provider.</li>
<li>Case-mix concentration via antenatal referral — high-risk pregnancies are transferred in utero to tertiary centres, so babies born at NICU trusts carry more unmeasured risk than gestation alone records. (Postnatal transfers cannot inflate a delivery trust’s rate in this model: an admission is attributed to the trust where the baby was born, not where the care was given.)</li>
<li>Residual case-mix — gestation alone is a thin proxy for clinical need. The sensitivity model (gestation + birth weight + Apgar) reduces but does not remove this.</li>
</ol>
<p>The ICC is therefore a useful signal that something at the provider level is driving variation, but it should not be reported as a clean estimate of variation in admission practice. Where it has been possible to decompose it — the <a href="#outlier-completeness">funnel-outlier diagnostic</a> — the evidence points to reporting breadth (what gets counted as an NCC day) as the dominant driver at the extremes. Providers in the tails may warrant follow-up, but an extreme estimate could equally reflect submission completeness, referral patterns, local thresholds for late-preterm admission, or case-mix not captured by gestation alone.</p>
<hr>
</section>
</section>
<section id="sensitivity-analysis-full-clinical-adjustment" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Sensitivity Analysis: Full Clinical Adjustment</h1>
<p>The sensitivity analysis adds birth weight and Apgar 5-minute score to the model, using 218,886 births with complete clinical data (43.2% of total). Birth weight uses the MSDS source only, for the reasons set out in Methods.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed caption-top table-sm small">
<caption>Sensitivity model: Full clinical adjustment</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Variable</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Odds Ratio</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">95% CI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Gestation_Weeks</td>
<td style="text-align: left;">Gestation (per week)</td>
<td style="text-align: right;">0.617</td>
<td style="text-align: center;">(0.61, 0.624)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Birth_Weight_kg</td>
<td style="text-align: left;">Birth weight (per kg)</td>
<td style="text-align: right;">0.907</td>
<td style="text-align: center;">(0.876, 0.94)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Apgar_5_Clean</td>
<td style="text-align: left;">Apgar 5-min (per point)</td>
<td style="text-align: right;">0.638</td>
<td style="text-align: center;">(0.629, 0.647)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ethnicity_Baby_GroupedWhite Other</td>
<td style="text-align: left;">Ethnicity: White Other</td>
<td style="text-align: right;">0.949</td>
<td style="text-align: center;">(0.898, 1.003)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ethnicity_Baby_GroupedMixed</td>
<td style="text-align: left;">Ethnicity: Mixed</td>
<td style="text-align: right;">0.954</td>
<td style="text-align: center;">(0.897, 1.014)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ethnicity_Baby_GroupedIndian</td>
<td style="text-align: left;">Ethnicity: Indian</td>
<td style="text-align: right;">1.163</td>
<td style="text-align: center;">(1.081, 1.251)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ethnicity_Baby_GroupedPakistani</td>
<td style="text-align: left;">Ethnicity: Pakistani</td>
<td style="text-align: right;">0.969</td>
<td style="text-align: center;">(0.903, 1.04)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ethnicity_Baby_GroupedBangladeshi</td>
<td style="text-align: left;">Ethnicity: Bangladeshi</td>
<td style="text-align: right;">1.165</td>
<td style="text-align: center;">(1.04, 1.304)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ethnicity_Baby_GroupedOther Asian</td>
<td style="text-align: left;">Ethnicity: Other Asian</td>
<td style="text-align: right;">1.015</td>
<td style="text-align: center;">(0.928, 1.109)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ethnicity_Baby_GroupedBlack</td>
<td style="text-align: left;">Ethnicity: Black</td>
<td style="text-align: right;">1.039</td>
<td style="text-align: center;">(0.974, 1.11)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ethnicity_Baby_GroupedChinese</td>
<td style="text-align: left;">Ethnicity: Chinese</td>
<td style="text-align: right;">0.761</td>
<td style="text-align: center;">(0.577, 1.003)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ethnicity_Baby_GroupedOther</td>
<td style="text-align: left;">Ethnicity: Other</td>
<td style="text-align: right;">0.950</td>
<td style="text-align: center;">(0.855, 1.056)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IMD_Quintile4</td>
<td style="text-align: left;">IMD: 4</td>
<td style="text-align: right;">1.038</td>
<td style="text-align: center;">(0.984, 1.095)</td>
</tr>
<tr class="even">
<td style="text-align: left;">IMD_Quintile3</td>
<td style="text-align: left;">IMD: 3</td>
<td style="text-align: right;">1.095</td>
<td style="text-align: center;">(1.039, 1.154)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IMD_Quintile2</td>
<td style="text-align: left;">IMD: 2</td>
<td style="text-align: right;">1.076</td>
<td style="text-align: center;">(1.021, 1.134)</td>
</tr>
<tr class="even">
<td style="text-align: left;">IMD_Quintile1 - Most deprived</td>
<td style="text-align: left;">IMD: 1 - Most deprived</td>
<td style="text-align: right;">1.094</td>
<td style="text-align: center;">(1.038, 1.153)</td>
</tr>
</tbody>
</table>
</div>
</div>
<section id="comparing-primary-and-sensitivity-models" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="comparing-primary-and-sensitivity-models"><span class="header-section-number">4.1</span> Comparing Primary and Sensitivity Models</h2>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed caption-top table-sm small">
<caption>Ethnicity effects: Primary vs Sensitivity model</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Ethnicity</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Primary OR</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Sensitivity OR</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Change</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Direction</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Ethnicity_Baby_GroupedWhite Other</td>
<td style="text-align: left;">White Other</td>
<td style="text-align: right;">0.924</td>
<td style="text-align: right;">0.949</td>
<td style="text-align: right;">0.025</td>
<td style="text-align: center;">↑ Increased</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ethnicity_Baby_GroupedMixed</td>
<td style="text-align: left;">Mixed</td>
<td style="text-align: right;">0.942</td>
<td style="text-align: right;">0.954</td>
<td style="text-align: right;">0.012</td>
<td style="text-align: center;">Stable</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ethnicity_Baby_GroupedIndian</td>
<td style="text-align: left;">Indian</td>
<td style="text-align: right;">1.054</td>
<td style="text-align: right;">1.163</td>
<td style="text-align: right;">0.109</td>
<td style="text-align: center;">↑ Increased</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ethnicity_Baby_GroupedPakistani</td>
<td style="text-align: left;">Pakistani</td>
<td style="text-align: right;">0.889</td>
<td style="text-align: right;">0.969</td>
<td style="text-align: right;">0.080</td>
<td style="text-align: center;">↑ Increased</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ethnicity_Baby_GroupedBangladeshi</td>
<td style="text-align: left;">Bangladeshi</td>
<td style="text-align: right;">1.060</td>
<td style="text-align: right;">1.165</td>
<td style="text-align: right;">0.105</td>
<td style="text-align: center;">↑ Increased</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ethnicity_Baby_GroupedOther Asian</td>
<td style="text-align: left;">Other Asian</td>
<td style="text-align: right;">1.013</td>
<td style="text-align: right;">1.015</td>
<td style="text-align: right;">0.002</td>
<td style="text-align: center;">Stable</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ethnicity_Baby_GroupedBlack</td>
<td style="text-align: left;">Black</td>
<td style="text-align: right;">1.037</td>
<td style="text-align: right;">1.039</td>
<td style="text-align: right;">0.002</td>
<td style="text-align: center;">Stable</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ethnicity_Baby_GroupedChinese</td>
<td style="text-align: left;">Chinese</td>
<td style="text-align: right;">0.695</td>
<td style="text-align: right;">0.761</td>
<td style="text-align: right;">0.066</td>
<td style="text-align: center;">↑ Increased</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ethnicity_Baby_GroupedOther</td>
<td style="text-align: left;">Other</td>
<td style="text-align: right;">0.926</td>
<td style="text-align: right;">0.950</td>
<td style="text-align: right;">0.024</td>
<td style="text-align: center;">↑ Increased</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed caption-top table-sm small">
<caption>Deprivation effects: Primary vs Sensitivity model</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th">IMD Quintile</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Primary OR</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Sensitivity OR</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Change</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Direction</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">IMD_Quintile4</td>
<td style="text-align: left;">4</td>
<td style="text-align: right;">1.016</td>
<td style="text-align: right;">1.038</td>
<td style="text-align: right;">0.022</td>
<td style="text-align: center;">↑ Increased</td>
</tr>
<tr class="even">
<td style="text-align: left;">IMD_Quintile3</td>
<td style="text-align: left;">3</td>
<td style="text-align: right;">1.063</td>
<td style="text-align: right;">1.095</td>
<td style="text-align: right;">0.032</td>
<td style="text-align: center;">↑ Increased</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IMD_Quintile2</td>
<td style="text-align: left;">2</td>
<td style="text-align: right;">1.108</td>
<td style="text-align: right;">1.076</td>
<td style="text-align: right;">-0.032</td>
<td style="text-align: center;">↓ Decreased</td>
</tr>
<tr class="even">
<td style="text-align: left;">IMD_Quintile1 - Most deprived</td>
<td style="text-align: left;">1 - Most deprived</td>
<td style="text-align: right;">1.101</td>
<td style="text-align: right;">1.094</td>
<td style="text-align: right;">-0.007</td>
<td style="text-align: center;">Stable</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Adding birth weight and Apgar moves some ethnicity coefficients materially (the largest change is 0.11 in odds-ratio terms, for the Pakistani and Indian groups), indicating that clinical case-mix explains part of the associations seen in the primary model; the deprivation coefficients are essentially unchanged (largest change 0.03). The sensitivity model provides fuller case-mix adjustment at the cost of a smaller sample. Hospital variation is essentially unaffected by the fuller adjustment: the ICC is 31.7% in the primary model and 30.4% in the sensitivity model, so between-trust variation remains substantial.</p>
<hr>
</section>
</section>
<section id="length-of-stay" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Length of Stay Among Admitted Babies</h1>
<p>The models above ask who <em>gets</em> NCC care; this section asks how much care admitted babies then receive. Unlike the timing analysis (Phase 2, on hold), length of stay does not depend on a birth datetime: the outcome is <code>NCC_CC_Total_Days</code>, a count of daily critical-care records, so it is available now.</p>
<p>Of the 57,072 admitted babies in the primary analysis sample, 53,090 (93%) have at least one CC daily record and form the length-of-stay sample. The remaining 3,982 are MSDS-only admissions with no CC records — their stay length is unobservable in this data, an exclusion to bear in mind if MSDS-only status is unevenly distributed across providers (it is; see the funnel section). Stay length is the total number of days with an NCC critical-care record within 90 days of birth, summed across care periods.</p>
<p>The distribution is heavily skewed — median 4 days (IQR 2–8), 99th percentile 86 days — and gestation dominates it: median stays run from 3 days at term to 61 days below 28 weeks. Any crude group comparison therefore mostly re-describes each group’s preterm mix.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed caption-top table-sm small">
<caption>Crude length of NCC stay (days) among admitted babies with CC records, FY 2023/24. Group differences concentrate in the tail: medians are identical, while the share of long stays varies.</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Group</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">n</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Median (IQR)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Mean</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Stay ≥28 days</th>
</tr>
</thead>
<tbody>
<tr class="odd" data-grouplength="10">
<td colspan="5" style="border-bottom: 1px solid"><strong>Ethnicity</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">White British</td>
<td style="text-align: right;">32,197</td>
<td style="text-align: right;">4 (2–8)</td>
<td style="text-align: right;">9.2</td>
<td style="text-align: right;">7.4%</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">White Other</td>
<td style="text-align: right;">4,580</td>
<td style="text-align: right;">4 (2–8)</td>
<td style="text-align: right;">9.5</td>
<td style="text-align: right;">7.9%</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Mixed</td>
<td style="text-align: right;">3,588</td>
<td style="text-align: right;">4 (2–8)</td>
<td style="text-align: right;">9.3</td>
<td style="text-align: right;">8.4%</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Indian</td>
<td style="text-align: right;">2,746</td>
<td style="text-align: right;">4 (2–9)</td>
<td style="text-align: right;">9.7</td>
<td style="text-align: right;">9.1%</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Pakistani</td>
<td style="text-align: right;">2,562</td>
<td style="text-align: right;">4 (2–10)</td>
<td style="text-align: right;">10.4</td>
<td style="text-align: right;">8.9%</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Bangladeshi</td>
<td style="text-align: right;">856</td>
<td style="text-align: right;">4 (2–8)</td>
<td style="text-align: right;">9.9</td>
<td style="text-align: right;">8.5%</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Other Asian</td>
<td style="text-align: right;">1,597</td>
<td style="text-align: right;">4 (2–8)</td>
<td style="text-align: right;">9.2</td>
<td style="text-align: right;">8.2%</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Black</td>
<td style="text-align: right;">3,636</td>
<td style="text-align: right;">4 (2–9)</td>
<td style="text-align: right;">11.5</td>
<td style="text-align: right;">11.1%</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Chinese</td>
<td style="text-align: right;">151</td>
<td style="text-align: right;">4 (2–9)</td>
<td style="text-align: right;">9.2</td>
<td style="text-align: right;">7.3%</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Other</td>
<td style="text-align: right;">1,177</td>
<td style="text-align: right;">4 (2–10)</td>
<td style="text-align: right;">11.6</td>
<td style="text-align: right;">11.6%</td>
</tr>
<tr class="even" data-grouplength="5">
<td colspan="5" style="border-bottom: 1px solid"><strong>IMD quintile</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">5 - Least deprived</td>
<td style="text-align: right;">8,147</td>
<td style="text-align: right;">4 (2–8)</td>
<td style="text-align: right;">9.0</td>
<td style="text-align: right;">7.5%</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">4</td>
<td style="text-align: right;">9,064</td>
<td style="text-align: right;">4 (2–8)</td>
<td style="text-align: right;">9.0</td>
<td style="text-align: right;">7.2%</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">3</td>
<td style="text-align: right;">10,032</td>
<td style="text-align: right;">4 (2–8)</td>
<td style="text-align: right;">9.1</td>
<td style="text-align: right;">7.4%</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">2</td>
<td style="text-align: right;">11,520</td>
<td style="text-align: right;">4 (2–8)</td>
<td style="text-align: right;">9.5</td>
<td style="text-align: right;">8.0%</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">1 - Most deprived</td>
<td style="text-align: right;">14,327</td>
<td style="text-align: right;">4 (2–10)</td>
<td style="text-align: right;">10.5</td>
<td style="text-align: right;">9.4%</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The crude pattern needs careful reading: every group’s median stay is 4 days, while mean stays and the share of long stays (≥28 days) look elevated for Black babies (mean 11.5 vs 9.2 for White British; 11.1% vs 7.4% staying ≥28 days) and for the most deprived quintile. Whether that reflects anything beyond case-mix is exactly what the adjusted model tests.</p>
<p>Stay length is modelled with a negative binomial mixed model (log link; the variance/mean ratio of ~28 rules out Poisson), with gestation entered as clinical bands — extremely/very/moderately/late preterm vs term — because its effect is far too nonlinear for a linear week term, plus ethnicity, IMD quintile, and a delivery-trust random intercept. Exponentiated coefficients are rate ratios: multiplicative differences in expected days of NCC care, conditional on gestation band and trust. BH adjustment is applied within the ethnicity and deprivation families, as elsewhere in this report.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed caption-top table-sm small">
<caption>Adjusted rate ratios for days of NCC care among admitted babies (negative binomial mixed model with delivery-trust random intercept).</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Variable</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Rate Ratio</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">95% CI</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p-value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p (BH-adj)</th>
</tr>
</thead>
<tbody>
<tr class="odd" data-grouplength="4">
<td colspan="5" style="border-bottom: 1px solid"><strong>Gestation (ref: Term 37w+)</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Extremely preterm (&lt;28w)</td>
<td style="text-align: right;">13.238</td>
<td style="text-align: center;">(12.754, 13.74)</td>
<td style="text-align: right;">&lt;0.001</td>
<td style="text-align: right;">—</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Very preterm (28-31w)</td>
<td style="text-align: right;">8.806</td>
<td style="text-align: center;">(8.569, 9.05)</td>
<td style="text-align: right;">&lt;0.001</td>
<td style="text-align: right;">—</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Moderate preterm (32-33w)</td>
<td style="text-align: right;">4.456</td>
<td style="text-align: center;">(4.343, 4.571)</td>
<td style="text-align: right;">&lt;0.001</td>
<td style="text-align: right;">—</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Late preterm (34-36w)</td>
<td style="text-align: right;">1.757</td>
<td style="text-align: center;">(1.729, 1.785)</td>
<td style="text-align: right;">&lt;0.001</td>
<td style="text-align: right;">—</td>
</tr>
<tr class="even" data-grouplength="9">
<td colspan="5" style="border-bottom: 1px solid"><strong>Ethnicity (ref: White British)</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">White Other</td>
<td style="text-align: right;">0.970</td>
<td style="text-align: center;">(0.946, 0.994)</td>
<td style="text-align: right;">0.014</td>
<td style="text-align: right;">0.041</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Mixed</td>
<td style="text-align: right;">0.986</td>
<td style="text-align: center;">(0.959, 1.013)</td>
<td style="text-align: right;">0.295</td>
<td style="text-align: right;">0.402</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Indian</td>
<td style="text-align: right;">1.015</td>
<td style="text-align: center;">(0.983, 1.048)</td>
<td style="text-align: right;">0.357</td>
<td style="text-align: right;">0.402</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Pakistani</td>
<td style="text-align: right;">1.086</td>
<td style="text-align: center;">(1.05, 1.122)</td>
<td style="text-align: right;">&lt;0.001</td>
<td style="text-align: right;">&lt;0.001</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Bangladeshi</td>
<td style="text-align: right;">1.097</td>
<td style="text-align: center;">(1.038, 1.159)</td>
<td style="text-align: right;">&lt;0.001</td>
<td style="text-align: right;">0.004</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Other Asian</td>
<td style="text-align: right;">1.027</td>
<td style="text-align: center;">(0.987, 1.068)</td>
<td style="text-align: right;">0.193</td>
<td style="text-align: right;">0.347</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Black</td>
<td style="text-align: right;">0.979</td>
<td style="text-align: center;">(0.952, 1.006)</td>
<td style="text-align: right;">0.13</td>
<td style="text-align: right;">0.292</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Chinese</td>
<td style="text-align: right;">0.940</td>
<td style="text-align: center;">(0.83, 1.064)</td>
<td style="text-align: right;">0.328</td>
<td style="text-align: right;">0.402</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Other</td>
<td style="text-align: right;">1.019</td>
<td style="text-align: center;">(0.974, 1.066)</td>
<td style="text-align: right;">0.412</td>
<td style="text-align: right;">0.412</td>
</tr>
<tr class="even" data-grouplength="4">
<td colspan="5" style="border-bottom: 1px solid"><strong>Deprivation (ref: Least Deprived)</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">IMD: 4</td>
<td style="text-align: right;">0.992</td>
<td style="text-align: center;">(0.969, 1.016)</td>
<td style="text-align: right;">0.528</td>
<td style="text-align: right;">0.635</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">IMD: 3</td>
<td style="text-align: right;">1.009</td>
<td style="text-align: center;">(0.986, 1.032)</td>
<td style="text-align: right;">0.454</td>
<td style="text-align: right;">0.635</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">IMD: 2</td>
<td style="text-align: right;">1.006</td>
<td style="text-align: center;">(0.983, 1.029)</td>
<td style="text-align: right;">0.635</td>
<td style="text-align: right;">0.635</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">IMD: 1 - Most deprived</td>
<td style="text-align: right;">1.032</td>
<td style="text-align: center;">(1.008, 1.056)</td>
<td style="text-align: right;">0.008</td>
<td style="text-align: right;">0.031</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="padding: 0; border: 0"><sup></sup> BH-adjusted p-values computed within each family (9 ethnicity contrasts; 4 IMD contrasts).</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
</tfoot>

</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-los-forest" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-los-forest-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="technical_appendix_files/figure-html/fig-los-forest-1.png" class="img-fluid figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-los-forest-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Adjusted rate ratios for length of NCC stay by ethnicity and deprivation (negative binomial mixed model, adjusted for gestation band, with hospital random effects). Gestation-band effects (RR 1.8–13.2) are omitted from the plot for scale.
</figcaption>
</figure>
</div>
</div>
</div>
<section id="what-adjustment-does-to-the-crude-picture" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="what-adjustment-does-to-the-crude-picture"><span class="header-section-number">5.1</span> What adjustment does to the crude picture</h2>
<p>The Black crude excess is entirely case-mix. After gestation-band adjustment the rate ratio for Black babies is 0.98 (0.95–1.01) — the 25% crude excess in mean stay disappears entirely, because Black babies’ longer average stays reflect their higher preterm rates, not longer stays at a given severity. Combined with the admission model (OR ~1.04) this extends the equitable-access finding: Black babies are admitted at parity <em>and</em>, once admitted, receive the expected quantity of care for their gestation.</p>
<p>Pakistani and Bangladeshi babies stay around 9–10% longer than expected. The two groups with the most interesting admission-model results are also the ones with adjusted stay excesses that survive BH correction: Pakistani 1.09 (1.05–1.12) and Bangladeshi 1.10 (1.04–1.16). For Pakistani babies the direction is notable: this group had ~11% <em>lower</em> adjusted odds of admission, and lower admission propensity combined with longer stays once admitted is the pattern one would expect if the effective admission threshold is higher — the marginal, milder cases don’t get admitted, so those who do are sicker and stay longer. This is a hypothesis, not a demonstration: greater within-gestation-band morbidity (e.g.&nbsp;growth restriction, congenital anomaly rates) would produce the same signature, and this model cannot separate the two. For Bangladeshi babies, whose admission odds were slightly <em>above</em> parity, the threshold reading does not fit, and residual severity is the more natural explanation. Either way, these are again the two groups that a broad “Asian” category would average away.</p>
<p>The deprivation gradient in stay length is almost entirely case-mix. The crude mean gap (10.5 vs 9.0 days, most vs least deprived) shrinks to a residual 3.2% (RR 1.03 (1.01–1.06)) — small, and consistent with the <a href="#imd-morbidity">unmeasured-need reading</a>: the model adjusts for gestation band but not for the growth restriction that rises with deprivation <em>within</em> gestation bands.</p>
<p>Trusts vary substantially in recorded stay length. The trust random-intercept SD (0.31 on the log scale) implies a trust one SD above average records ~36% longer stays than expected for its case-mix. This should not be read as pure clinical practice: the <a href="#outlier-completeness">funnel diagnostic</a> showed that what gets <em>counted</em> as an NCC day varies markedly between trusts, and that recording breadth flows directly into this outcome. The stay-length measure here is “days carrying an NCC critical-care record”, not independently verified cot-days.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Reading length of stay conditional on admission
</div>
</div>
<div class="callout-body-container callout-body">
<p>This analysis conditions on admission, which is itself the outcome of the earlier models. If a group’s admission threshold differs, its admitted babies are a differently-selected slice of the same underlying population — which changes expected stay length without any difference in care received. Rate ratios here should therefore be read jointly with the admission model, never in isolation. The Pakistani finding above is the concrete example: its interpretation depends directly on the admission result.</p>
</div>
</div>
<hr>
</section>
</section>
<section id="mortality" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Mortality Among Live Births: A Descriptive Look</h1>
<p>The final feedback item asks about outcomes. This section is deliberately descriptive — no regression model, and heavier caveats than elsewhere in this report — because death ascertainment in this extract is partial in ways that could differ between groups. MBRRACE-UK, with linked death registrations, is the authoritative source on neonatal mortality inequalities; the purpose here is the narrower one of checking whether the mortality patterns visible in this data are consistent with the access findings above.</p>
<section id="measuring-death-in-this-data" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="measuring-death-in-this-data"><span class="header-section-number">6.1</span> Measuring death in this data</h2>
<p>Mirroring the dual-source design of the NCC admission flag, a baby is counted as having died if either source records it: the MSDS death date (deaths known to the maternity service), or — added in a July 2026 extract refresh — a hospital spell in APCS ending with discharge method “died”, which also captures deaths <em>after</em> maternity discharge in any hospital, up to the end of the extract window (30 April 2024). Among 504,392 live births, 1,448 deaths are recorded (2.87 per 1,000): 731 in both sources, 593 in APCS only and 124 in MSDS only. The two sources corroborate each other well — where both record a death, 685 of 731 (94%) agree on the date to within a day — but neither alone is complete: MSDS sees 59% of the combined total and APCS 91%. A further 45 babies recorded as live births in MSDS but coded as stillbirths in APCS were removed as vital-status-uncertain.</p>
<p>Three properties of this flag must be kept in view. First, it means “death recorded in hospital or by the maternity service within the extract window”, not 28-day neonatal mortality. With no day of birth available in this environment, age at death cannot be computed, so no clinically standard mortality window can be constructed. Second, follow-up is uneven: a baby born in March 2024 has around two months of in-window observation against thirteen for an April 2023 birth. In practice this matters little — recorded death rates are flat across birth months (2.6–3.1 per 1,000, with no decline at the end of the year), as expected when most in-hospital infant deaths occur close to birth. Third, deaths outside hospital after discharge are invisible here, and that invisibility need not be evenly distributed across groups.</p>
<p>The flag behaves as clinical reality would predict: rates run from 270 per 1,000 below 28 weeks’ gestation to 0.8 per 1,000 at term — a gradient of roughly 350-fold — and NCC-admitted babies die at 12.3 per 1,000 against 1.6 among the never-admitted.</p>
</section>
<section id="crude-rates-and-gestation-standardised-ratios" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="crude-rates-and-gestation-standardised-ratios"><span class="header-section-number">6.2</span> Crude rates and gestation-standardised ratios</h2>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed caption-top table-sm small">
<caption>Crude recorded deaths per 1,000 live births (either source), FY 2023/24. Wilson 95% confidence intervals.</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Group</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">n</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Deaths</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Rate per 1,000 (95% CI)</th>
</tr>
</thead>
<tbody>
<tr class="odd" data-grouplength="10">
<td colspan="4" style="border-bottom: 1px solid"><strong>Ethnicity</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">White British</td>
<td style="text-align: right;">274,346</td>
<td style="text-align: right;">630</td>
<td style="text-align: right;">2.3 (2.1–2.5)</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">White Other</td>
<td style="text-align: right;">53,186</td>
<td style="text-align: right;">92</td>
<td style="text-align: right;">1.7 (1.4–2.1)</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Mixed</td>
<td style="text-align: right;">34,367</td>
<td style="text-align: right;">98</td>
<td style="text-align: right;">2.9 (2.3–3.5)</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Indian</td>
<td style="text-align: right;">24,857</td>
<td style="text-align: right;">59</td>
<td style="text-align: right;">2.4 (1.8–3.1)</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Pakistani</td>
<td style="text-align: right;">25,764</td>
<td style="text-align: right;">157</td>
<td style="text-align: right;">6.1 (5.2–7.1)</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Bangladeshi</td>
<td style="text-align: right;">8,682</td>
<td style="text-align: right;">28</td>
<td style="text-align: right;">3.2 (2.2–4.7)</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Other Asian</td>
<td style="text-align: right;">14,627</td>
<td style="text-align: right;">47</td>
<td style="text-align: right;">3.2 (2.4–4.3)</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Black</td>
<td style="text-align: right;">31,733</td>
<td style="text-align: right;">177</td>
<td style="text-align: right;">5.6 (4.8–6.5)</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Chinese</td>
<td style="text-align: right;">1,811</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">3.3 (1.5–7.2)</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Other</td>
<td style="text-align: right;">12,506</td>
<td style="text-align: right;">43</td>
<td style="text-align: right;">3.4 (2.6–4.6)</td>
</tr>
<tr class="even" data-grouplength="5">
<td colspan="4" style="border-bottom: 1px solid"><strong>IMD quintile</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">5 - Least deprived</td>
<td style="text-align: right;">80,556</td>
<td style="text-align: right;">147</td>
<td style="text-align: right;">1.8 (1.6–2.1)</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">4</td>
<td style="text-align: right;">88,479</td>
<td style="text-align: right;">188</td>
<td style="text-align: right;">2.1 (1.8–2.5)</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">3</td>
<td style="text-align: right;">94,909</td>
<td style="text-align: right;">245</td>
<td style="text-align: right;">2.6 (2.3–2.9)</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">2</td>
<td style="text-align: right;">108,260</td>
<td style="text-align: right;">316</td>
<td style="text-align: right;">2.9 (2.6–3.3)</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">1 - Most deprived</td>
<td style="text-align: right;">127,034</td>
<td style="text-align: right;">522</td>
<td style="text-align: right;">4.1 (3.8–4.5)</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The crude pattern echoes the national picture: rates for Pakistani (6.1 (5.2–7.1) per 1,000) and Black (5.6 (4.8–6.5)) babies run at roughly twice the White British rate (2.3 (2.1–2.5)), and the most deprived quintile at roughly twice the least deprived. But crude rates largely re-describe each group’s prematurity mix, so — in place of another regression — each group’s observed deaths are compared with the number expected given its gestational-age distribution (indirect standardisation over the five gestation bands used in the length-of-stay analysis; exact Poisson intervals; BH adjustment within families; 2,675 babies with missing or implausible gestation are excluded here — note they carry a grossly elevated death rate, 291 deaths, so the standardised analysis is slightly conservative).</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed caption-top table-sm small">
<caption>Observed vs expected deaths, standardised for gestational age (expected counts from national gestation-band-specific rates). O/E above 1: more deaths than the group's gestational mix predicts.</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Group</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">n</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Observed</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Expected</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">O/E (95% CI)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p (BH-adj)</th>
</tr>
</thead>
<tbody>
<tr class="odd" data-grouplength="10">
<td colspan="6" style="border-bottom: 1px solid"><strong>Ethnicity</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">White British</td>
<td style="text-align: right;">273,403</td>
<td style="text-align: right;">519</td>
<td style="text-align: right;">565.3</td>
<td style="text-align: right;">0.92 (0.84–1.00)</td>
<td style="text-align: right;">0.135</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">White Other</td>
<td style="text-align: right;">52,912</td>
<td style="text-align: right;">68</td>
<td style="text-align: right;">108.4</td>
<td style="text-align: right;">0.63 (0.49–0.80)</td>
<td style="text-align: right;">&lt;0.001</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Mixed</td>
<td style="text-align: right;">34,201</td>
<td style="text-align: right;">84</td>
<td style="text-align: right;">76.8</td>
<td style="text-align: right;">1.09 (0.87–1.35)</td>
<td style="text-align: right;">0.654</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Indian</td>
<td style="text-align: right;">24,470</td>
<td style="text-align: right;">48</td>
<td style="text-align: right;">56.4</td>
<td style="text-align: right;">0.85 (0.63–1.13)</td>
<td style="text-align: right;">0.573</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Pakistani</td>
<td style="text-align: right;">25,642</td>
<td style="text-align: right;">122</td>
<td style="text-align: right;">67.6</td>
<td style="text-align: right;">1.80 (1.50–2.15)</td>
<td style="text-align: right;">&lt;0.001</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Bangladeshi</td>
<td style="text-align: right;">8,643</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">21.4</td>
<td style="text-align: right;">1.07 (0.68–1.61)</td>
<td style="text-align: right;">0.833</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Other Asian</td>
<td style="text-align: right;">14,474</td>
<td style="text-align: right;">36</td>
<td style="text-align: right;">38.2</td>
<td style="text-align: right;">0.94 (0.66–1.30)</td>
<td style="text-align: right;">0.898</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Black</td>
<td style="text-align: right;">31,474</td>
<td style="text-align: right;">134</td>
<td style="text-align: right;">113.3</td>
<td style="text-align: right;">1.18 (0.99–1.40)</td>
<td style="text-align: right;">0.135</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Chinese</td>
<td style="text-align: right;">1,804</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">4.1</td>
<td style="text-align: right;">1.23 (0.40–2.86)</td>
<td style="text-align: right;">0.833</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Other</td>
<td style="text-align: right;">12,440</td>
<td style="text-align: right;">34</td>
<td style="text-align: right;">33.8</td>
<td style="text-align: right;">1.01 (0.70–1.41)</td>
<td style="text-align: right;">0.931</td>
</tr>
<tr class="even" data-grouplength="5">
<td colspan="6" style="border-bottom: 1px solid"><strong>IMD quintile</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">5 - Least deprived</td>
<td style="text-align: right;">80,202</td>
<td style="text-align: right;">117</td>
<td style="text-align: right;">151.6</td>
<td style="text-align: right;">0.77 (0.64–0.92)</td>
<td style="text-align: right;">0.011</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">4</td>
<td style="text-align: right;">88,089</td>
<td style="text-align: right;">149</td>
<td style="text-align: right;">175.4</td>
<td style="text-align: right;">0.85 (0.72–1.00)</td>
<td style="text-align: right;">0.076</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">3</td>
<td style="text-align: right;">94,348</td>
<td style="text-align: right;">189</td>
<td style="text-align: right;">204.7</td>
<td style="text-align: right;">0.92 (0.80–1.06)</td>
<td style="text-align: right;">0.368</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">2</td>
<td style="text-align: right;">107,445</td>
<td style="text-align: right;">249</td>
<td style="text-align: right;">254.6</td>
<td style="text-align: right;">0.98 (0.86–1.11)</td>
<td style="text-align: right;">0.754</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">1 - Most deprived</td>
<td style="text-align: right;">126,505</td>
<td style="text-align: right;">425</td>
<td style="text-align: right;">353.7</td>
<td style="text-align: right;">1.20 (1.09–1.32)</td>
<td style="text-align: right;">0.001</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mortality-oe" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mortality-oe-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="technical_appendix_files/figure-html/fig-mortality-oe-1.png" class="img-fluid figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mortality-oe-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: Gestation-standardised mortality ratios (observed/expected recorded deaths) by ethnicity and deprivation, with exact Poisson 95% intervals. Dashed line: deaths in line with the group’s gestational-age mix. Descriptive only — ascertainment caveats in the text apply.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="what-standardisation-does-to-the-crude-picture" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="what-standardisation-does-to-the-crude-picture"><span class="header-section-number">6.3</span> What standardisation does to the crude picture</h2>
<p>The Black crude excess is mostly gestational mix. After standardisation the Black O/E is 1.18 (0.99–1.40) — the crude doubling largely reflects higher preterm rates, the same mechanism as the length-of-stay finding. The residual leans above 1 without reaching significance; MBRRACE, with full death-registration linkage and richer adjustment, does find a genuine residual excess for Black babies, so the near-parity here should be read as limited power and crude adjustment, not as contradicting it.</p>
<p>The Pakistani excess is not gestational mix. Pakistani babies show 80% more recorded deaths than their gestational-age distribution predicts (O/E 1.80 (1.50–2.15), BH-adjusted p &lt; 0.001) — the strongest signal in this section, and consistent with MBRRACE findings of elevated perinatal mortality for babies of Pakistani ethnicity at every gestation, in which congenital anomalies are a documented contributor. Set alongside this report’s other Pakistani findings — around 11% lower adjusted odds of NCC admission, and around 9% longer stays once admitted — a consistent picture emerges of a group with higher within-gestation clinical need whose access does not appear correspondingly higher. All three signals point to the same follow-up: severity at admission (see <a href="modelling_results.html#recommendations">Recommendation 6</a> in the Findings report).</p>
<p>The deprivation gradient survives standardisation. The most deprived quintile records 20% more deaths than its gestational mix predicts (O/E 1.20 (1.09–1.32)) and the least deprived 23% fewer (0.77 (0.64–0.92)), a monotone gradient across quintiles. As with the <a href="#deprivation">admission-model gradient</a>, this is consistent with deprivation-linked morbidity <em>within</em> gestation bands (growth restriction rises with deprivation even among term babies — see the <a href="#imd-morbidity">morbidity check</a>).</p>
<p>One estimate is implausibly low. White Other babies record 37% <em>fewer</em> deaths than expected (O/E 0.63 (0.49–0.80), BH-adjusted p &lt; 0.001). A genuinely lower risk is possible, but this group plausibly includes families with stronger ties abroad, and a death after leaving the country — or after transfer out of NHS hospital care — is invisible to both sources. This is a concrete reminder that ascertainment, as well as risk, can differ by group — which is why this section stays descriptive.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>What this mortality flag is not
</div>
</div>
<div class="callout-body-container callout-body">
<p>This is not neonatal mortality as nationally defined: no age at death can be computed (no day of birth in this environment), deaths are only visible while in hospital or known to the maternity service, and the observation window is administrative (to 30 April 2024) rather than clinical (28 days). Group comparisons assume ascertainment is equal across groups, which the White Other result suggests may not hold. These figures are an internal consistency check on this dataset’s access findings — for population inequalities in neonatal mortality, MBRRACE-UK perinatal surveillance is the appropriate reference.</p>
</div>
</div>
<hr>
</section>
</section>
<section id="limitations" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Limitations</h1>
<ol type="1">
<li><p>Clinical covariate completeness: Birth weight is recorded for ~46% of births and Apgar for ~79%; jointly they limit the sensitivity model to under half the cohort. The primary model uses gestation alone to preserve sample size.</p></li>
<li><p>Single year of data: Results may not generalise to other time periods.</p></li>
<li><p>Residual confounding: While ethnicity is now disaggregated (e.g., Indian, Pakistani, Bangladeshi separately), within-group heterogeneity remains. Black ethnicities are still grouped together in the model.</p></li>
<li><p>Selection bias: Analysis restricted to births with complete data (94% of all births) — though the retained share is high and similar across providers (see the funnel diagnostic).</p></li>
<li><p>Outcome definition: “NCC admission” is whatever providers record as NCC in two administrative sources, and the funnel diagnostic shows the breadth of that recording varies materially between providers. The outcome is best read as “received care recorded as NCC”, not “occupied a critical care cot”.</p></li>
</ol>
<hr>
</section>
<section id="technical-details" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Technical Details</h1>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Model Specification (click to expand)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Model 2 - Primary (Gestation only):</p>
<pre><code>NCC_Admitted ~ Gestation_Weeks + Ethnicity_Baby_Grouped + IMD_Quintile + (1 | Delivery_Trust)</code></pre>
<p>Model 3 - Sensitivity (Full clinical adjustment):</p>
<pre><code>NCC_Admitted ~ Gestation_Weeks + Birth_Weight_kg + Apgar_5_Clean +
               Ethnicity_Baby_Grouped + IMD_Quintile + (1 | Delivery_Trust)</code></pre>
<p><code>Delivery_Trust</code> is constructed in the modelling script as <code>coalesce(LEFT(Delivery_Site_Code, 3), Submitting_Org_Code)</code> — see Methods (Random-effect grouping) for the rationale.</p>
<ul>
<li>Family: Binomial (logit link)</li>
<li>Estimation: Maximum likelihood via Laplace approximation</li>
<li>Optimizer: bobyqa</li>
<li>Package: lme4 version 2.0.1</li>
</ul>
<p>Note on birth weight data: The sensitivity model uses <code>Birth_Weight_Grams</code> (MSDS source only) rather than <code>Birth_Weight_Combined</code> to avoid differential missingness bias. The combined variable has 94% completeness for NCC babies (due to CC data fallback) vs 46% for non-NCC babies, which would inflate NCC rates in complete case analysis.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Model 1: Fixed Effects Only (click to expand)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>A standard logistic regression on the same sample, without trust random intercepts — retained as a reference point for the mixed-effects models.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed caption-top table-sm small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Variable</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Odds Ratio</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">95% CI</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p-value</th>
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd" data-grouplength="1">
<td colspan="5" style="border-bottom: 1px solid"><strong>Clinical</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Gestation (per week)</td>
<td style="text-align: right;">0.654</td>
<td style="text-align: center;">(0.651, 0.657)</td>
<td style="text-align: right;">&lt;0.001</td>
<td style="text-align: left;">***</td>
</tr>
<tr class="odd" data-grouplength="9">
<td colspan="5" style="border-bottom: 1px solid"><strong>Ethnicity (ref: White British)</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Ethnicity: White Other</td>
<td style="text-align: right;">0.770</td>
<td style="text-align: center;">(0.744, 0.795)</td>
<td style="text-align: right;">&lt;0.001</td>
<td style="text-align: left;">***</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Ethnicity: Mixed</td>
<td style="text-align: right;">0.876</td>
<td style="text-align: center;">(0.843, 0.909)</td>
<td style="text-align: right;">&lt;0.001</td>
<td style="text-align: left;">***</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Ethnicity: Indian</td>
<td style="text-align: right;">0.885</td>
<td style="text-align: center;">(0.847, 0.925)</td>
<td style="text-align: right;">&lt;0.001</td>
<td style="text-align: left;">***</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Ethnicity: Pakistani</td>
<td style="text-align: right;">0.713</td>
<td style="text-align: center;">(0.681, 0.746)</td>
<td style="text-align: right;">&lt;0.001</td>
<td style="text-align: left;">***</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Ethnicity: Bangladeshi</td>
<td style="text-align: right;">0.715</td>
<td style="text-align: center;">(0.662, 0.77)</td>
<td style="text-align: right;">&lt;0.001</td>
<td style="text-align: left;">***</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Ethnicity: Other Asian</td>
<td style="text-align: right;">0.871</td>
<td style="text-align: center;">(0.823, 0.921)</td>
<td style="text-align: right;">&lt;0.001</td>
<td style="text-align: left;">***</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Ethnicity: Black</td>
<td style="text-align: right;">0.925</td>
<td style="text-align: center;">(0.89, 0.962)</td>
<td style="text-align: right;">&lt;0.001</td>
<td style="text-align: left;">***</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Ethnicity: Chinese</td>
<td style="text-align: right;">0.608</td>
<td style="text-align: center;">(0.507, 0.724)</td>
<td style="text-align: right;">&lt;0.001</td>
<td style="text-align: left;">***</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Ethnicity: Other</td>
<td style="text-align: right;">0.723</td>
<td style="text-align: center;">(0.677, 0.771)</td>
<td style="text-align: right;">&lt;0.001</td>
<td style="text-align: left;">***</td>
</tr>
<tr class="odd" data-grouplength="4">
<td colspan="5" style="border-bottom: 1px solid"><strong>Deprivation (ref: Least Deprived)</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">IMD: 4</td>
<td style="text-align: right;">0.988</td>
<td style="text-align: center;">(0.957, 1.021)</td>
<td style="text-align: right;">0.486</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">IMD: 3</td>
<td style="text-align: right;">1.013</td>
<td style="text-align: center;">(0.981, 1.046)</td>
<td style="text-align: right;">0.447</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">IMD: 2</td>
<td style="text-align: right;">1.031</td>
<td style="text-align: center;">(0.999, 1.064)</td>
<td style="text-align: right;">0.055</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">IMD: 1 - Most deprived</td>
<td style="text-align: right;">1.022</td>
<td style="text-align: center;">(0.991, 1.054)</td>
<td style="text-align: right;">0.163</td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>
</div>
</div>
<p><small>Significance: *** p&lt;0.001, ** p&lt;0.01, * p&lt;0.05</small></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Model Fit Statistics (click to expand)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed caption-top table-sm small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Metric</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Model 2 (Primary)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Model 3 (Sensitivity)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Number of observations</td>
<td style="text-align: right;">476,475</td>
<td style="text-align: right;">218,886</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of trusts (groups)</td>
<td style="text-align: right;">131</td>
<td style="text-align: right;">77</td>
</tr>
<tr class="odd">
<td style="text-align: left;">AIC</td>
<td style="text-align: right;">275,073.8</td>
<td style="text-align: right;">120,048.6</td>
</tr>
<tr class="even">
<td style="text-align: left;">BIC</td>
<td style="text-align: right;">275,251</td>
<td style="text-align: right;">120,234</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Log-likelihood</td>
<td style="text-align: right;">-137,520.9</td>
<td style="text-align: right;">-60,006.3</td>
</tr>
<tr class="even">
<td style="text-align: left;">Deviance</td>
<td style="text-align: right;">274,183.7</td>
<td style="text-align: right;">119,549</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
</div>
<hr>
<p>Report generated: 2026-07-21 14:56:58.077784</p>
<p>R version: R version 4.6.1 (2026-06-24 ucrt)</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>